### ISSUE TITLE
Fix sample code on extended_stats_bucket

### ISSUE THREAD

**Issue by jambanagar** [elastic/docs#101]
should be "buckets_path" not  "buckets_paths".... (no 's' at the end_)

        "stats_monthly_sales": {
            "extended_stats_bucket": {
                "buckets_paths": "sales_per_month>sales" 
            }
        }

**Comment by clintongormley** [comment]
Hi @jambanagar 

You should open this issue against the elasticsearch repo, which contains the source docs.  Also, there is an "edit me" button next to each header in the docs, which allows you to send a PR directly
