### ISSUE TITLE
#anchor links within a page have a wrong start position 

### ISSUE THREAD

**Issue by uric** [elastic/docs#102]
They need to be offset to adjust for the fixed header on the page. e.g. when clicking the "Node" link in the basic concepts page of the Elasticsearch 2.3 docs.
https://www.elastic.co/guide/en/elasticsearch/reference/current/_basic_concepts.html#_node 

![image](https://cloud.githubusercontent.com/assets/167374/16713375/5cc414c0-46ae-11e6-9a5a-cacad7353e63.png)

**Comment by matschaffer** [comment]
Noticed this on watcher 1 & 2 docs as well - https://www.elastic.co/guide/en/watcher/current/input.html#input-search

I tried a couple of options from http://nicolasgallagher.com/jump-links-and-viewport-positioning/ but couldn't find anything that "just works".

**Comment by clintongormley** [comment]
There's already an issue open for this on https://github.com/elastic/website-www.elastic.co/issues/1057
