### ISSUE TITLE
Move to root-relative URLs for links between books

### ISSUE THREAD

**Issue by lcawl** [elastic/docs#1029]
Most of the Elastic documentation now uses attributes to fill in the URL for links between books. For example, in https://github.com/elastic/stack-docs/blob/7.3/docs/en/install-upgrade/installing-stack.asciidoc:

> Install the Elastic Stack products you want to use in the following order:
> . Elasticsearch ({ref}/install-elasticsearch.html[install instructions])
> . Kibana ({kibana-ref}/install.html[install])
> . Logstash ({logstash-ref}/installing-logstash.html[install])
> . Beats ({beats-ref}/getting-started.html[install instructions])
> . APM Server ({apm-server-ref-70}/installing.html[install instructions])
> . Elasticsearch Hadoop ({hadoop-ref}/install.html[install instructions])

These attributes ( {ref}, {kibana-ref}, etc) are defined in https://github.com/elastic/docs/blob/master/shared/attributes.asciidoc

We should consider changing the values in those attributes such that they're root-relative instead of specifying the full URL. This would make the links work better in scenarios where we're providing a full set of offline documentation.

It would mean you wouldn't be able to check your links if you're building a single book, however. Since we do link checks when we build *all* documentation, however, and that's the build we're running in our PR checks now, I think that is okay.

**Comment by nik9000** [comment]
I think we'll need #1229 first, but after that I think it'll help quite a bit to do the switch. It'll prevent "accidentally escaping" from the previews, for example.
