### ISSUE TITLE
More whitespace between 2+ line nav items

### ISSUE THREAD

**Issue by jrodewig** [elastic/docs#1035]
@albertzaharovits pointed out that nav items with multiple lines tend to be a bit too close in the nav sidebar.

Here's an example from https://www.elastic.co/guide/en/elastic-stack-overview/7.3/oidc-guide-authentication.html

<img width="341" alt="Screen Shot 2019-08-05 at 12 00 47 PM" src="https://user-images.githubusercontent.com/40268737/62478428-13a4bd00-b779-11e9-8ec9-7504f66aa37b.png">

**Comment by nik9000** [comment]
I did this one! They used to be so far apart you couldn't tell that they were the same line. They are a little crowded now.
