### ISSUE TITLE
404 page doesn't have new style

### ISSUE THREAD

**Issue by bmorelli25** [elastic/docs#1058]
Docs 404s still have the old style: [Example](https://www.elastic.co/guide/en/apm/agent/js-base/msaster/index.html).

Regular site 404s are on the new style: [Example](https://www.elastic.co/elasticodn/).

**Comment by debadair** [comment]
Still appears to be the case. Perhaps we can treat this as a "feature" and create a customized 404 page for docs that provided a search box, links back to landing page, TOC for the book you were trying to get to, etc?

**Comment by nik9000** [comment]
I believe the current plan for hosting the docs will have the docs-preview application owning the 404 page. And all the other error pages for that matter. So, yes, we can customize it.

**Comment by bmorelli25** [comment]
Yes, this looks fixed to me as well.
