### ISSUE TITLE
Special information sections (notes, tips, etc) are breaking element boundaries in dark background sections

### ISSUE THREAD

**Issue by mikeisonthenets** [elastic/docs#1066]
First discovered earlier today on: https://www.elastic.co/guide/en/cloud/current/ec-securing-clusters-SAML.html

![image](https://user-images.githubusercontent.com/4106008/62975017-46306480-bdce-11e9-828b-c7d681573347.png)

And also seen on: https://www.elastic.co/guide/en/cloud-enterprise/2.2/ece-add-custom-bundle-plugin.html

**Comment by nik9000** [comment]
Thanks for filing this! I wonder what #1065 will do for it....

**Comment by nik9000** [comment]
> Thanks for filing this! I wonder what #1065 will do for it....

Yeah, that pretty much fixes it:

![2019-08-13-163753_1481x932_scrot](https://user-images.githubusercontent.com/215970/62975593-bc41c500-bde8-11e9-8ca5-849e83402a9b.png)

**Comment by nik9000** [comment]
I've merged #1065 which should make this better. The docs build is currently doing a full rebuild and will be for another 20 minutes or so. The next build should pick up right after that and take another five minutes. That should pick up my fix. So, give it about half an hour.

**Comment by nik9000** [comment]
This should be fixed now. The ttl on the styles is a day so you might have to force reload.
