### ISSUE TITLE
Language switcher is confusing when language doesn't exist

### ISSUE THREAD

**Issue by bmorelli25** [elastic/docs#1113]
It's not clear that a language isn't available for a code block. I'm only seeing this in the `master` branch of the Elasticsearch reference.

Example: https://www.elastic.co/guide/en/elasticsearch/reference/7.x/dynamic-mapping.html

I'd expect to be able to hover over the "!" for more information, but I'm unable to. Switching languages also has no impact on what's displayed.

<img width="575" alt="Screen Shot 2019-08-28 at 8 02 58 PM" src="https://user-images.githubusercontent.com/5618806/63907081-f1e0d380-c9ce-11e9-831b-d2bc78835575.png">

---

In other branches the dropdown doesn't exist.
<img width="569" alt="Screen Shot 2019-08-28 at 8 03 06 PM" src="https://user-images.githubusercontent.com/5618806/63907080-f0171000-c9ce-11e9-8ad6-c7507d0128b2.png">

cc @nik9000

**Comment by nik9000** [comment]
> I'm only seeing this in the `master` branch of the Elasticsearch reference.

Right. We've intentionally kept this feature only on the master branch because we expect things like this.

> I'd expect to be able to hover over the "!" for more information, but I'm unable to. Switching languages also has no impact on what's displayed.

This is just sitting on my backlog of stuff to do, though I'm being pulled in a different direction and might try to bring in @JoshMock because he'd be able to do it faster than I ever could. But he also has a backlog of stuff.

**Comment by bmorelli25** [comment]
Ahh, my bad. I didn't realize this was expected in `master`.

**Comment by nik9000** [comment]
Not at all! It is nice to have it called out publicly.

**Comment by JoshMock** [comment]
@nik9000 I may have time this week to give that tooltip situation a look, actually! The main overhead to be aware of is that I haven't set up docs locally yet, so I'd need to get my bearings first.

**Comment by bmorelli25** [comment]
Nice! Thank you.

**Comment by JoshMock** [comment]
The Jenkins bots have done their magic and the `master` docs now contain the tooltip. Example here: https://www.elastic.co/guide/en/elasticsearch/reference/master/dynamic-mapping.html
