### ISSUE TITLE
Add an external link checker

### ISSUE THREAD

**Issue by geekpete** [elastic/docs#112]
This might be more of a live monitoring problem to solve but nice to catch before docs get published as well as a multi-pronged approach.

Add an external link checker to see if about to be published docs point to an offsite url that doesn't load as expected, eg 404 or site down.

This example is more a result of old links going bad due to referenced sites changing, but noticed a 404 link from this page that got me thinking of ways to improve documentation quality around links:
https://www.elastic.co/blog/found-fuzzy-search

Links to:
http://exploringelasticsearch.com/book/searching-natural-language/searching-non-word-text.html

**Comment by geekpete** [comment]
Just realised that this functionality might already be part of this codebase and that I didn't check for it before logging this ticket, feel free to close this ticket if it exists already.

**Comment by clintongormley** [comment]
@geekpete please open this on the website repo, not docs
