### ISSUE TITLE
Allow horizontal rule in docs

### ISSUE THREAD

**Issue by gchaps** [elastic/docs#1130]
I'd like to create a landing page that uses horizontal rules between sections, similar to [this page](https://stripe.com/docs).  When I follow the instructions in the [asciidoctor quick ref for thematic breaks](https://asciidoctor.org/docs/asciidoc-syn), nothing happens. 

It would be nice to get horizontal rules working.

**Comment by nik9000** [comment]
The page you linked doesn't look like it has any horizontal rules. Those are under each section which is something we might should talk to @Adrian-J about doing globally.

**Comment by debadair** [comment]
For @gchaps case, it feels more like something that should be implemented via CSS style characteristic than via hardcoding horizontal rules. (Though rendering manually inserted "thematic breaks" would be a handy stop-gap.)

**Comment by Adrian-J** [comment]
@gchaps @nik9000 @debadair This is going to be a part of the new design. I'm not sure how urgent this request is, but elements like this will be considered in the new version.

**Comment by gchaps** [comment]
Thanks, @Adrian-J .  It's not urgent, so including it as part of the new design is great.

**Comment by gtback** [comment]
Marking this as blocked, since we'll just include it when we do the re-design.

**Comment by dedemorton** [comment]
@gchaps Can we close this issue since there are workarounds in asciidoctor (using html passthru blocks), and the problem will be fixed in the new system.
