### ISSUE TITLE
Don't index PR previews

### ISSUE THREAD

**Issue by bmorelli25** [elastic/docs#1152]
PR Previews are starting to show up in search engine results. It probably makes sense not to index these. cc @nik9000 
<img width="631" alt="Screen Shot 2019-09-05 at 2 05 42 PM" src="https://user-images.githubusercontent.com/5618806/64381610-6d9ed980-cfe8-11e9-816b-914605b89f6a.png">

**Comment by nik9000** [comment]
I fixed this in #1013 but never deployed it....

**Comment by nik9000** [comment]
I'm deploying the update now.

**Comment by bmorelli25** [comment]
Thanks Nik!

**Comment by nik9000** [comment]
This *should* be live now.

**Comment by nik9000** [comment]
If you see more hits please put them here an reopen it.
