### ISSUE TITLE
Search button broken

### ISSUE THREAD

**Issue by nik9000** [elastic/docs#1165]
The search button on the docs isn't working. This is technically part of the chrome so it'll be fixed in the website repo, but I'm creating this here for tracking because that repo is private.

**Comment by brianjolly** [comment]
Thanks @nik9000! We should have a fix up hopefully tonight.

**Comment by nik9000** [comment]
The search button is working for me now.

**Comment by debadair** [comment]
There still appear to be some issues--it works the first time, but subsequent clicks on the search icon in new tabs don't bring up the search UI.

**Comment by nik9000** [comment]
@brianjolly, could you have a look at this? Everything feels ok to me but Deb knows better than I do.

**Comment by brianjolly** [comment]
Sure thing @nik9000!

Also tracking here https://github.com/elastic/website-www.elastic.co/issues/4586

**Comment by debadair** [comment]
Fixed.
