### ISSUE TITLE
Adding //CONSOLE tags to examples in list items breaks the list rendering

### ISSUE THREAD

**Issue by debadair** [elastic/docs#117]
The attached asciidoc reproduces the problem--the output is shown in console-list-issue-a.png. Removing the //CONSOLE directives generates the output shown in console-list-issue-b.png.

[console-list-issue.txt](https://github.com/elastic/docs/files/475559/console-list-issue.txt)

![console-list-issue-a](https://cloud.githubusercontent.com/assets/362578/18567225/fc5aee60-7b4b-11e6-9628-ca6607faa987.png)

![console-list-issue-b](https://cloud.githubusercontent.com/assets/362578/18567226/fc5ee3d0-7b4b-11e6-938a-34c44e718fbf.png)

**Comment by clintongormley** [comment]
@debadair you need to use [open blocks](http://www.methods.co.nz/asciidoc/userguide.html#X29) with this markup, eg:

    
. Create a role that has the `manage_index_templates` and
    `monitor` cluster privileges, and `read`, `write`, and `create_index`
    privileges for the indices the Beat creates. You can create roles from the
    **Management > Roles** UI in Kibana or through the `role` API.
    For example, the following request creates a `packetbeat_writer` role:
    +
    --
    [source, sh]
    ---------------------------------------------------------------
    POST _xpack/security/role/packetbeat_writer
    {
      "cluster": ["manage_index_templates", "monitor"],
      "indices": [
        {
          "names": [ "packetbeat-*" ], <1>
          "privileges": ["read","write","create_index"]
        }
      ]
    }
    ---------------------------------------------------------------
    //CONSOLE
    <1> If you use a custom Packetbeat index pattern, specify that pattern
    instead of the default `packetbeat-*` pattern.
    --

    . Assign the writer role to the user the Beat is going to use to
    connect to Elasticsearch:


Note the extra `--` lines
