### ISSUE TITLE
Support a non-local/configurable ES cluster in the web scripts

### ISSUE THREAD

**Issue by elasticdog** [elastic/docs#118]
Per our discussion regarding the current docs building setup with Jenkins, it would be nice if the [web/base.pl](https://github.com/elastic/docs/blob/18cefb7f230adfa615379eb9756e646a0d080bb7/web/base.pl#L28) and [web/irc_bot.pl](https://github.com/elastic/docs/blob/18cefb7f230adfa615379eb9756e646a0d080bb7/web/irc_bot.pl#L19) scripts could support a configurable ES cluster rather than hard-coding the localhost as the connection endpoint.

This would allow us to migrate to a more-reliable and easier to maintain setup of running ES in Elastic Cloud, and then hosting each of the search and IRC services in dedicated containers rather than having them intermixed on the host with the regular crawling/building Jenkins jobs. The ultimate goal of being able to migrate away from the legacy build-us-00 and onto elasticsearch-ci.

I don't know enough perl to write up a PR, but would think that even checking for an environment variable, and defaulting to localhost if one doesn't exist would work out cleanly?

**Comment by elasticdog** [comment]
The _web/base.pl_ changes to support this were pushed via 0f37859b063ade76433a35baa940a36d0a49ee15.

**Comment by gtback** [comment]
@elasticdog is this relevant anymore or can we close it?

**Comment by elasticdog** [comment]
Nice archeological dig @gtback! This can definitely be closed out now, as the whole docs architecture from the time this was written no longer exists.
