### ISSUE TITLE
Documentation build should be aware of changes to shared file attributes

### ISSUE THREAD

**Issue by lcawl** [elastic/docs#1180]
Related to https://github.com/elastic/docs/issues/804

With more and more books using shared files (such as https://github.com/elastic/docs/blob/master/shared/attributes.asciidoc and https://github.com/elastic/docs/tree/master/shared/versions/stack), it is increasingly important for the build to be aware of when changes occur in those files and re-build the appropriate books.  

Currently, the only way to ensure that all of the appropriate books pick up the changes is to rebuild *all* books, which is overkill. 

Alternatively, if the builds can't track which books need to be rebuilt, it would be nice to be able to select which books to rebuild (since we have a wiki page that lists all the books that use shared files).  This would be less ideal than an automated solution, however, since it relies on the wiki being up-to-date.

**Comment by nik9000** [comment]
I believe we have this now with #1297, #1295, #1294, and #1256.
