### ISSUE TITLE
Changes to shared files in beats/libbeat do not trigger rebuild of Beats books

### ISSUE THREAD

**Issue by dedemorton** [elastic/docs#1183]
We have many shared files in Beats that are reused across several books.

When we update the shared files under beats/libbeat/docs, it seems that the doc build is not detecting the change and rebuilding all affected books.

I thought we'd fixed this awhile back, but now I'm not sure...because the problem still exists.

Here's a PR that was merged 5 days ago and (as of the creating of this issue) has not been picked up:

https://github.com/elastic/beats/pull/13504

As we move to including more sections in other books (like the stack overview), this problem will become even more significant.

**Comment by lcawl** [comment]
Related to https://github.com/elastic/docs/issues/1180

**Comment by dedemorton** [comment]
Closing because I discovered that the problem that provoked this issue was author error, not build error.
