### ISSUE TITLE
Document best practices for content reuse

### ISSUE THREAD

**Issue by dedemorton** [elastic/docs#1196]
Content reuse is great, but builds dependencies between projects and makes it more difficult for external contributors to update docs.

Before we go hog wild with tagged regions, let's come up with some best practices around content reuse and identify strategies for creating shared content that's easier to consume.

**Comment by dedemorton** [comment]
I'm going to dump some raw info here because I'm seeing stuff during the asciidoctor migration that we should avoid.

- [ ] Avoid using tagged regions to include content that contains ifdefs and ifevals.

**Comment by benskelker** [comment]
Don't know if this make any sense at all, and it would be loads of work for Nik even if it does, so just throwing out an idea for using unique IDs:

1. Tag content you want to reuse in the source file and open a PR
2. The elasticsearch-ci/docs build creates a unique ID for the tagged content and displays it somewhere in the console output 
3. Use the ID in the target file
4. Resolve content reuse links during doc builds

What happens when the target file is merged but the PR for the source content is not? Only allow target file merges after the source file is merged?

Loads of disadvantages (file walk to resolve links and the need to dynamically add the link somewhere in the transform process) and may not even be doable, but it would give us robust content reuse and the ability to easily see and track all sources and targets.

**Comment by debadair** [comment]
It would be really helpful to have some authoring tooling that enabled you to introspect the source files and see all of the places where topics and tagged regions are included. And, conversely, easily open included topics to make modifications. It wouldn't really help with the contributor problem, but it would  make it a little easier for Elastic folks to understand the implications of their changes.

**Comment by debadair** [comment]
WRT unique IDs, I think the way Antora handled this was that everything was scoped based on IDs set in the playbooks. I'd worry about having to author using generated IDs instead of being able to discover them from just looking at the source.

**Comment by dedemorton** [comment]
A group of us have been discussing approaches to content reuse. @lcawl created a PR that shows what it might look like to house shared content about monitoring in the docs repo: 
https://github.com/elastic/docs/pull/1370

After reviewing this PR, I have some concerns about chopping the content into a lot of small pieces and housing it outside of the main content repos. It just doesn't feel right to me, especially given the limitations of our current authoring environment. I worry that reuse at this level of granularity:

- Makes the content difficult to update, especially for external contributors, because it removes the content from the main flow. 
- Makes the content prone to getting stale over time. Because the content would live outside the project repo, developers are likely to overlook it when they make changes.
- Complicates the PR creation and backporting process for developers who need to submit code plus doc changes (a requirement for some groups).

**Comment by benskelker** [comment]
Dede's [gdoc on content reuse](https://docs.google.com/document/d/1XmptxWoKE2QAyxhNjBT4aDkUJuh0siy31NAodNM0870/edit#heading=h.ru5xx3bm0nw2).

**Comment by lcawl** [comment]
I agree with the concerns about breaking content into smaller pieces shared in a separate location.  However, when we leave the pieces in situ, to re-use them we must:

. Increase the list of dependencies that folks must check out to pull the content from the appropriate repos. Perhaps this is less of a concern now that we have preview builds and less folks have to figure out how to build books individually.
. Figure out a way to remind folks that updating details within the tagged regions has widespread impact and must be tested/verified appropriately. E.g. If someone changes the instructions in the Kibana page such that it no longer works in the other contexts.

**Comment by dedemorton** [comment]
I agree. I don't think we should be reusing content across repos unless the content is in a shared location (to minimize dependencies). However, we need to be very careful about what we put into our "library" of reusable content. Just within the Beats project itself, I've noticed problems with chunks of "reused" content (especially small chunks) being overlooked during updates:

* Some contributors don't even look at the HTLM output. If the doc build passes, they think the change is OK. They only think about the content that they see in the file they're updating.
* I've heard from contributors who are put off by the complexity of the source files. With a few exceptions, I'm the only person dealing with the backlog of doc defects, which means I have *a lot* of very old doc issues. I think my reuse strategy is partly to blame for this. People are reluctant to make updates when it's not obvious where the source lives.
* When things break, they break horribly, and because content reuse makes the files more fragile and harder to understand, I often need to help folks sort out doc build problems (though hopefully Nik's improvements to error reporting will fix that). 

I don't think we should reuse at the sentence level if the content is vital to the completion of the task. If two tasks are very similar and we want to reuse content for that reason, it might make sense to have the full task defined in one file, and maybe use variables and/or conditional coding to make it specific to where it's used.

I'll do more thinking about this. The Beats docs are a rat king of conditional coding. I'm hoping we can find a way to balance the desire to write once with the need to make content that everyone can update.

**Comment by dedemorton** [comment]
Wanted to add to what I said before (as if I haven't said enough words...hehe). I think/hope that our architecture changes will make some of the duplicated content unnecessary (should be true if we organize around user goals rather than product silos).

**Comment by dedemorton** [comment]
Closing because this issue is quite old and focuses on asciidoc.
