### ISSUE TITLE
Make Elasticsearch docs open in Console editor popup closeable

### ISSUE THREAD

**Issue by clintongormley** [elastic/docs#120]
_From @lukas-vlcek on September 29, 2016 9:38_

**Elasticsearch version**: Documentation for 5.x

**Description of the problem including expected versus actual behavior**:

Make the popup window closeable (add Close input '[X]' or 'ESC' key listener).

![view_in_console](https://cloud.githubusercontent.com/assets/205174/18948722/88ce028c-8638-11e6-8764-9b7b07393a90.jpg)

_Copied from original issue: elastic/elasticsearch#20693_

**Comment by clintongormley** [comment]
_From @lukas-vlcek on September 29, 2016 9:39_

Oh, obviously, the popup is shown when the Settings icon is clicked, not the "VIEW IN CONSOLE" link.

**Comment by clintongormley** [comment]
_From @jasontedor on September 29, 2016 15:26_

This is for our docs, I see. I've changed the title to make that clearer.

**Comment by clintongormley** [comment]
_From @lukas-vlcek on September 29, 2016 16:10_

Thanks @jasontedor

**Comment by gtback** [comment]
It looks like there's an `x` to close this window now.
