### ISSUE TITLE
Font and background colors for important items

### ISSUE THREAD

**Issue by aleph-zero** [elastic/docs#125]
Customers often miss important items in our documents even though we call out these times with a visual block and an icon that says "important". 

I believe we should consider making these important blocks of text a brighter color so as to call out their significance. See the attached picture as an example. The grey background really makes it blend in to the overall documentation. Maybe a red font title or something similar would be a better visual cue.

![alert](https://cloud.githubusercontent.com/assets/452273/19818141/5d2b3136-9d03-11e6-8d75-0c196a863ed1.png)

**Comment by dedemorton** [comment]
The design team is currently working on a redesign of the site.
