### ISSUE TITLE
"es$(...).devbridgeAutocomplete is not a function" error breaks search bar

### ISSUE THREAD

**Issue by prondzyn** [elastic/docs#1266]
From time to time (but quite often) I see a bug in the browser console:

> Uncaught TypeError: es$(...).devbridgeAutocomplete is not a function

and when it occurs, the search lens button stops working - the search bar is not opening at all.

![search_lens_not_working](https://user-images.githubusercontent.com/5822647/66394346-2fc11680-e9d5-11e9-8dae-bc23e4a6fe8d.png)

My Chrome browser version is 77.0.3865.90 but I observed this issue on other browsers as well. Guessing that some JS library sometimes is loading to slow but it is required by other code.

**Comment by nik9000** [comment]
@brianjolly, could you have a look at this one?

**Comment by brianjolly** [comment]
Yes, hoping to have a fix for this one soon.

**Comment by nik9000** [comment]
@brianjolly, is this one fixed?

**Comment by brianjolly** [comment]
Hi @nik9000! Yes, this one has been resolved. Thanks for checking :)
