### ISSUE TITLE
add docs at the leftmost position in the breadcrums

### ISSUE THREAD

**Issue by zumo64** [elastic/docs#127]
That would simplify the navigation between documentations , for example if you are in the definitive guide and would like to check the reference guide .. 

We could have "docs" (or something else) as the root for all documentation

**Comment by clintongormley** [comment]
I know it isn't very obvious, but the `Docs` header at the top of the page is actually a link, and takes you where you want to go

**Comment by zumo64** [comment]
ah thanks @clintongormley I can't believe I didn't check Docs , sorry for the noise
