### ISSUE TITLE
Links broken on Metricbeat Reference index page

### ISSUE THREAD

**Issue by ycombinator** [elastic/docs#1274]
All links on this page are broken: https://www.elastic.co/guide/en/beats/metricbeat

The links take the user to pages with URLs like https://www.elastic.co/guide/en/beats/7.2/index.html (which doesn't exist and results in a 404). Instead the links should take the user to pages with URLs like https://www.elastic.co/guide/en/beats/metricbeat/7.2/index.html. So it looks like the beat name is not being inserted into the link URL.

**Comment by nik9000** [comment]
@ycombinator, how did you get that url? Is it linked somewhere?

**Comment by ycombinator** [comment]
I'm afraid I manually typed it in. I was looking at a Filebeat doc page and wanted to navigate to Metricbeat docs so I typed in the URL https://www.elastic.co/guide/en/beats/metricbeat hoping it would take me to the right starting place.

**Comment by ycombinator** [comment]
BTW I just realized the same thing is happening on https://www.elastic.co/guide/en/beats/filebeat as well, FWIW.

**Comment by nik9000** [comment]
> I'm afraid I manually typed it in. I was looking at a Filebeat doc page and wanted to navigate to Metricbeat docs so I typed in the URL https://www.elastic.co/guide/en/beats/metricbeat hoping it would take me to the right starting place.

Got it!

We used to redirect from there to `/index.html` and all the links have always been relative to `index.html`. I'm tracking down why we don't redirect.

**Comment by nik9000** [comment]
> BTW I just realized the same thing is happening on https://www.elastic.co/guide/en/beats/filebeat as well, FWIW.

Yeah, it'll be every page where we serve `index.html` instead of redirect.

**Comment by nik9000** [comment]
This should be fixed now!
