### ISSUE TITLE
Links to repositories for logstash plugins

### ISSUE THREAD

**Issue by robin13** [elastic/docs#128]
Often when I'm browsing the logstash plugins pages I want to jump to the relevant repository, and have to first go to https://github.com/logstash-plugins/ then search for the name, and click on the repository.  Sometimes I click too fast and click on the `logstash-input-<thing>` rather than `logstash-output-<thing>` repository by accident... it would be lovely to have a link to the relevant repository on the docs page, and apart from helping lazy-me, I think it could inspire more community interaction if it is easier to find the repository (many people won't know to go to https://github.com/logstash-plugins/ to search for the repository).

**Comment by ph** [comment]
In https://github.com/elastic/logstash/pull/5720 I have added the link to the github repo in the plugin docs page so when its merged and the doc get generated with that new code we will have it.

**Comment by clintongormley** [comment]
Closing in favour of elastic/logstash#5720
