### ISSUE TITLE
Make it obvious that Docs is an active link

### ISSUE THREAD

**Issue by dedemorton** [elastic/docs#132]
It's not clear (especially for new users) that "Docs" (see below) is an active link.  Now that we've removed the Doc link from the main site nav, users might have trouble navigating back to the main docs page. At the very least, we should make "Docs" blue so it looks like all the other links on the page. 

![doclink](https://cloud.githubusercontent.com/assets/14206422/20198390/3c4547c6-a759-11e6-8cbc-1b3cfaf91d3b.png)

**Comment by clintongormley** [comment]
This issue was moved to elastic/website-www.elastic.co#1344
