### ISSUE TITLE
Mobile vs desktop seems reversed in Chrome?

### ISSUE THREAD

**Issue by jdivy** [elastic/docs#1377]
It's not entirely clear to me where this should be reported, but the 'docs generator' seems close enough for now.  For some time now Chrome thinks the elastic documentation is mobile when looking at it on a desktop, and it's quite annoying.  Apologies in advance if this should have been reported elsewhere (surely I'm not the only one who experiences this phenomenon), but for me this happens on blog posts as well.  When I toggle Chrome Dev Tools to 'Mobile' it appears to me what should be a Desktop view.

![Elastic_docs_as_desktop](https://user-images.githubusercontent.com/3937510/67979342-08cbbe00-fbea-11e9-85eb-b72a4dc018f5.png)

**Comment by nik9000** [comment]
@brianjolly this might be for you because it hits blog posts as well.

@jdivy, I haven't used Chrome in a few years and never used their dev tools much so I'm not entirely sure what you are describing. Is this "just" an issue with the dev tools or does it manifest in funny layout? I can't quite tell from your image what is going on. @brianjolly knows much more about this sort of thing than I do so maybe it'll just make sense to him.

**Comment by brianjolly** [comment]
Hello @jdivy, thanks for the report! We will try to get this working for you.

Our mobile breakpoint is at about 768 width. Looking at your screenshot, you have the width set at 918 width, so it should be showing the desktop view. The text and logo in your screenshot look very big if the window is set to 918 width. Could you double check your zoom level? Or do you have any custom font size settings in your browser?

You should be seeing something more like this:

<img width="1006" alt="Screen Shot 2019-11-01 at 10 00 17 AM" src="https://user-images.githubusercontent.com/140304/68042412-0de34880-fc90-11e9-8cc4-ee1e96b0900a.png">

cc. @cnbishop

**Comment by jdivy** [comment]
wow.  just checked on another computer and it's fine...you are correct sir - zoom level stuck at 250% and I hadn't noticed.  Sorry for the distraction for something so silly.

**Comment by brianjolly** [comment]
No worries @jdivy, thanks for confirming!

**Comment by jdivy** [comment]
I thought I was going crazy - thanks for your excellent work and excellent documentation!
