### ISSUE TITLE
"Copy as curl" feature needs to trim the path

### ISSUE THREAD

**Issue by consulthys** [elastic/docs#139]
When using the "copy as curl" feature on [this page](https://www.elastic.co/guide/en/elasticsearch/reference/current/_testing_analyzers.html) (and probably many others), there's a space between the path and the `?pretty` query string argument in the second and third commands, but not in the first one:

```
curl -XPUT 'localhost:9200/my_index?pretty' -d'
{
...
}'
curl -XGET 'localhost:9200/my_index/_analyze ?pretty' -d'
{
  "analyzer": "std_folded", 
  "text":     "Is this déjà vu?"
}'
curl -XGET 'localhost:9200/my_index/_analyze ?pretty' -d'
{
  "field": "my_text", 
  "text":  "Is this déjà vu?"
}'
```

This probably means that after applying the regular expression on the console text, the `path` might need to be trimmed before appending `?pretty` or `&pretty`.

The result of this issue is that the curl command errors out.

**Comment by clintongormley** [comment]
thanks @consulthys - fixed
