### ISSUE TITLE
Empty lines are not honored in a horizontal definition list

### ISSUE THREAD

**Issue by sophiec20** [elastic/docs#140]
https://www.elastic.co/guide/en/elasticsearch/reference/current/_profiling_queries.html#_all_parameters_3

The source looks like it tried to display a new paragraph, however the published web content does not contain any spacing.

Viewed in Chrome and Safari.

![asciidoc](https://cloud.githubusercontent.com/assets/4185750/21683024/6869466e-d34f-11e6-84c4-e5bb9bb9a6e2.png)
---
![web](https://cloud.githubusercontent.com/assets/4185750/21683028/69de2712-d34f-11e6-9d7e-3dc56f5aca1c.png)

**Comment by nrichers** [comment]
@sophie, just a + between paragraphs should do it, but there is an issue with parapgraph formatting at the moment (there is a separate issue for that somewhere I believe).

**Comment by sophiec20** [comment]
Tried that.. but maybe I still had indents wrong.

**Comment by nrichers** [comment]
@sophiec20 Try removing the indents and possibly the extra line between the definition and the term? Forcing a new paragraph break does work, see this example (which also shows the formatting problem I mentioned earlier :-) ):

![image](https://cloud.githubusercontent.com/assets/15148011/21686537/a3b2b172-d31a-11e6-80eb-de6fbc2426b6.png)

**Comment by clintongormley** [comment]
This will work:

    [float]
    ==== All parameters

    [horizontal]
    `create_weight`::
    +
    --
    First para....

    Second para....
    --

    `build_scorer`::
    +
    --
    First para...

    Second para....
    --

The `+` says that the next line should be in the context of the previous line.  The `--` starts and ends a block whose contents should all be in the same context.
