### ISSUE TITLE
Disable edit links in non-maintained versions

### ISSUE THREAD

**Issue by debadair** [elastic/docs#1407]
Currently, the edit links show up for all pages in all versions if the source is in a public repo. This leads to PRs being opened against versions that we otherwise wouldn't touch. Those fixes often get "lost" because they aren't forward ported, and forward porting them is difficult due to the constant evolution of the docs.

The simplest option is to remove the edit button for select versions of a book. Trying to redirect to current/master/whatever doesn't work for the same reasons that forward porting is non-trivial. 

We could leave the edit buttons and pop up a message that asks the user to open a PR against master, but I'm not sure that's much friendlier than removing the edit button entirely. (Because using the version picker to switch to master  might just get you the "This page is not available in the docs for version:master" message.)

We might want to consider changing the default "You are looking at documentation for an older release" message to explicitly state that the version is no longer being updated

**Comment by zuketo** [comment]
+1, I like the proposal to remove the edit button completely for non-maintained/EOL versions. I also like the idea of using stronger language in the top message. A competitor uses the wording "This version of the manual is no longer supported." for EOL versions, maybe something along those lines?

**Comment by nik9000** [comment]
Closed by #1533.
