### ISSUE TITLE
copy-as-curl should include content-type

### ISSUE THREAD

**Issue by clintongormley** [elastic/docs#143]
With https://github.com/elastic/elasticsearch/pull/22691, the content-type header will become mandatory for HTTP requests with bodies.  copy-as-curl should be updated to include that header.

/cc @nik9000 in case you pick it up before i do

**Comment by nik9000** [comment]
> /cc @nik9000 in case you pick it up before i do

I think I might be able to grab it now if you like.

**Comment by clintongormley** [comment]
thanks @nik9000
