### ISSUE TITLE
Console editor popup 'Save' seems to be for current page only

### ISSUE THREAD

**Issue by william0901** [elastic/docs#147]
If you save console editor setting, it seems to be for that particular page only. If you navigate to another page, it will not work anymore.

From browser cookie, it's showing the console_url is pointing to only a specific path instead of elastic.co. Below is a screenshot:

![screen shot 2017-02-14 at 3 55 19 pm](https://cloud.githubusercontent.com/assets/14193849/22920228/ec929d34-f2ce-11e6-86c3-c4c84b60eae2.png)

**Comment by clintongormley** [comment]
thanks for reporting @william0901
