### ISSUE TITLE
content being covered by navigation menu

### ISSUE THREAD

**Issue by tsouza** [elastic/docs#148]
Part of the content in the docs about [migrating from shield](https://www.elastic.co/guide/en/x-pack/5.2/security-migration.html) seems to be covered by the navigation menu. 

This is what I see:
![screen shot 2017-02-17 at 11 37 38](https://cloud.githubusercontent.com/assets/122435/23071277/e18f4b24-f514-11e6-80d2-c9622f3e2fe6.png)

Might be related to https://github.com/elastic/docs/issues/138

**Comment by tsouza** [comment]
Another page with the same issue: https://www.elastic.co/guide/en/kibana/current/settings.html

<img width="1440" alt="screen shot 2017-04-04 at 15 11 11" src="https://cloud.githubusercontent.com/assets/122435/24671757/0dcfda0c-1949-11e7-92e4-7c815cf1ea7c.png">

**Comment by gtback** [comment]
It looks like the CSS has been updated to avoid this problem.
