### ISSUE TITLE
Repo size growth

### ISSUE THREAD

**Issue by nik9000** [elastic/docs#153]
I wonder if we could slow down the growth of this repository some. It is already twice the size of Elasticsearch and pretty slow to work with. I *think* this is because we commit the generated docs. I wonder if we could instead build them to wherever we serve them from.

**Comment by clintongormley** [comment]
I've been wanting to move the HTML docs into a separate repo which we can reset on a regular basis, so that the size doesn't get out of hand.

I just need to find the time to do it

**Comment by perryn** [comment]
Just popping in to mention that the repository is now too large for me to fully clone. 
It takes too long and github hangs up on me before it is complete.

I had to get a shallow clone like this:
 git clone --depth 1 https://github.com/elastic/docs.git

**Comment by dedemorton** [comment]
We purged to minimize this problem and plan to split when we do the doc infra changes.

**Comment by debadair** [comment]
We've got this, now (built-docs).
