### ISSUE TITLE
Link to javadocs

### ISSUE THREAD

**Issue by eskibars** [elastic/docs#154]
We recently started publishing javadocs at https://artifacts.elastic.co/javadoc/org/elasticsearch/<project>/<version>/index.html

It'd be great to link the associated java projects/clients to these docs, e.g.:
- [ ] https://www.elastic.co/guide/en/elasticsearch/client/java-api/[VERSION]/transport-client.html to https://artifacts.elastic.co/javadoc/org/elasticsearch/elasticsearch/[VERSION]/index.html?org/elasticsearch/client/transport/TransportClient.html)
- [ ] Somewhere under https://www.elastic.co/guide/en/elasticsearch/client/java-rest/[VERSION]/_getting_started.html to https://artifacts.elastic.co/javadoc/org/elasticsearch/client/rest/[VERSION]/index.html

**Comment by clintongormley** [comment]
This issue was moved to elastic/elasticsearch#23761
