### ISSUE TITLE
Curator shows wrong "preliminary documentation " message

### ISSUE THREAD

**Issue by Stacey-Gammon** [elastic/docs#155]
I think anyway... since elasticsearch 5.0 is already released, I'm not sure why I'm seeing the below message at the top.  It has the 4.2 version marked as "current".  Maybe this is intentional and curator is different than es?

<img width="1533" alt="screen shot 2017-03-24 at 12 23 35 pm" src="https://cloud.githubusercontent.com/assets/16563603/24303614/0781ec86-108d-11e7-980d-27ccda597120.png">

**Comment by clintongormley** [comment]
Curator is different from ES
