### ISSUE TITLE
Add repository names to paths when building documentation

### ISSUE THREAD

**Issue by lcawl** [elastic/docs#157]
Now that we are creating documentation that includes source files from multiple repositories (e.g. X-Pack reference, which currently uses the x-pack, x-pack-kibana, and x-pack-elasticsearch repositories), it would be very helpful for the full doc builds to extract the source files into repo folders.   For example, on my local clones of the repos, I have the following (peer) directories:

docs/
x-pack/
x-pack-kibana/
x-pack-elasticsearch/

I run the build-docs.pl command from this root directory, and it creates great output.  I'm hoping something similar can occur for the full doc builds.

As it currently stands, I think the full doc builds merge the source files at a lower level and it is highly likely that files will be accidentally overwritten (I can't guarantee that all repos will have unique subfolder names or filenames). I also currently need to create {foo-dir} variables and insert different path names depending on whether I'm doing a local or full build, due to this variance in paths.  I think this issue would resolve that disparity.

If this description is unclear or you need any further information or testing, please just let me know!

**Comment by lcawl** [comment]
@clintongormley and @debadair just wanted to note here that when this is accomplished, we can remove the local-index.asciidoc files in the x-pack repositories.

**Comment by clintongormley** [comment]
I started looking at this and it is harder than I initially expected, but will return to it when I can

**Comment by lcawl** [comment]
Since @debadair determined that the Elasticsearch and Logstash engineers nest the x-pack-* repos (see https://wiki.elastic.co/display/DOC for nesting), it seems like the ideal would be for all builds to use the same directory layout.  i.e. all of us building x-pack docs would structure our local directories to match what Elasticsearch and Logstash are doing, and the "build_docs.pl --all" would do the same (while still avoiding the merging described in the original problem).  
Otherwise we need to do lots of conditional {foo-dir} work-arounds and considerations for each build environment. (As indicated by discussions on #techpubs between @clintongormley and Deb today.
