### ISSUE TITLE
Update docs to include a H1 on all pages

### ISSUE THREAD

**Issue by zuketo** [elastic/docs#1614]
Hi @AnneB-SEO I've created an issue in the docs repo for tracking work to add h1 tags. From your original issue:

"All pages would benefit from having a H1 heading. Currently sub topics start with a H2 and do not have a H1.

This change would improve the ability for crawlers to identify the page topic and improve ranking. While there is some debate within the SEO community around the importance of H1s, we performed our own evaluation and found a significant ranking increase after adding H1s to a number of different content types."

**Comment by AnneB-SEO** [comment]
Thanks @zuketo !!!
