### ISSUE TITLE
Automatically rebuild docs when using the --open flag

### ISSUE THREAD

**Issue by ycombinator** [elastic/docs#162]
When working on docs, I use the `--open` flag to open up the generated HTML docs in my browser. If I then make changes to the docs source, I have to re-run `build_docs.pl` manually to re-generate the docs.

As an added convenience it would be nice if the docs would be automatically rebuilt upon changes, when the `--open` flag is in use.

**Comment by clintongormley** [comment]
@ycombinator the whole doc has to be rebuilt which (depending on the book) could take a minute ir more, plus it is CPU intensive.  I don't think we should support this
