### ISSUE TITLE
Make the Edit button work for Cloud docs! 

### ISSUE THREAD

**Issue by nrichers** [elastic/docs#1629]
Enabling the **Edit** button for Cloud docs would be easy, if it weren't for the fact that those docs today live in a private repo. But there are still many people who do have access to the elastic/cloud repo, and so ... 

... if we could figure out a way to enable the Edit button for those who do have access to the elastic/cloud repo, that would make quick docs changes so much simpler, not to mention that it would remove the Cloud writers as gatekeepers from the process. 

Two possible options: 
* Fancy: Figure out if you are a part of the Elastic org and display the **Edit** button if you are. I would think that if you use the new Elastic Cloud home page and are authenticated, we'd know who you are. Essentially, we'd be enabling the Edit button if you made it past SSO. 
* Minimally viable: Just enable the **Edit** button but mark it as Elastic-only or restricted with an icon or text if it's displayed on a Cloud docs page. Could be a simple as this:
   
   ![image](https://user-images.githubusercontent.com/15148011/70946501-17d8c500-200c-11ea-809b-443b04e69f5f.png)

@ppf2 @Leaf-Lin @nik9000 FYI

(I hope this is in the right repo, since we're talking about docs in a private repo. If this is not acceptable, let me know and I will move the issue.)

**Comment by ppf2** [comment]
LOVE IT ❤️

**Comment by nrichers** [comment]
@kellyemurphy raised a good point today: we also have the tooltip we can update, so that it clearly indicates you need to have access to the closed elastic/cloud repo:

![image](https://user-images.githubusercontent.com/15148011/71288478-e7e93480-231f-11ea-80b1-0e9c6808c677.png)

We could say something like `Requires access to edit this page on GitHub` or something like this.
