### ISSUE TITLE
Sense: Generic copy option for source text

### ISSUE THREAD

**Issue by alexfrancoeur** [elastic/docs#166]
In writing the [Timelion getting started guide](https://github.com/elastic/kibana/pull/11065) I found a need for the ability to copy an expression. Currently, timelion cannot accept multiple lines of input and the expression is listed as one long string. 

<img width="818" alt="screen shot 2017-04-17 at 8 02 16 am" src="https://cloud.githubusercontent.com/assets/25181823/25088418/37fb5676-2344-11e7-8eee-d548af9053ec.png">

For usability sake, it would be extremely valuable to have a copy option similar to "Copy as CURL" or "View in Console". I can imagine other source texts in docs needing a similar feature as well.

**Comment by dedemorton** [comment]
Closing in favor of https://github.com/elastic/docs/issues/319
