### ISSUE TITLE
extra-title-page content not displaying when building all docbooks

### ISSUE THREAD

**Issue by jrodewig** [elastic/docs#1689]
It looks like the legal notice content in the Elasticsearch [`index-extra-title-page.html` file](https://github.com/elastic/elasticsearch/blob/master/docs/reference/index-extra-title-page.html) is not displaying on the book's index page:

https://www.elastic.co/guide/en/elasticsearch/reference/master/index.html

After doing some local tests, I discovered the page _does_ display when building only the Elasticsearch Reference guide, but not if building all Elastic docs.

### Steps to recreate locally

1. Ensure you've pulled the latest changes into your local `elastic/docs` repo.
2. From the Elasticsearch repo, run the following command to build all Elastic docs:
```
$GIT_HOME/docs/build_docs --all --target_repo git@github.com:elastic/built-docs.git --open
```
Note that the legal notice content does _not_ display.

3. Stop the build command and run the following command to build only the Elasticsearch reference docs:
```
$GIT_HOME/docs/build_docs --doc $GIT_HOME/elasticsearch/docs/reference/index.asciidoc --resource=$GIT_HOME/elasticsearch/x-pack/docs/ --chunk 1 --open
```
Note that the legal notice content displays.

### Unsuccessful solutions
I renamed the `index-extra-title-page.html` file to `index-.x-extra-title-page.html` as a test. However, this failed to show the content for either the all build or the ES-only build.

**Comment by jrodewig** [comment]
Tagging @nik9000  in case you've got any ideas. No worries if not.

**Comment by nik9000** [comment]
Does it show up if you do:
```
$GIT_HOME/docs/build_docs --doc $GIT_HOME/elasticsearch/docs/reference/index.x.asciidoc --resource=$GIT_HOME/elasticsearch/x-pack/docs/ --chunk 1 --open
```
?

**Comment by jrodewig** [comment]
@nik9000 Yes, it does.

**Comment by nik9000** [comment]
Well then! I'm not really sure. I can certainly do some debugging in the morning.

**Comment by jrodewig** [comment]
Sounds good. This isn't a big deal or a big rush. This content was only displaying in master.

I'm not a Perl expert (or even dabbler), but I wonder if it has anything to do with `build_single` vs. `build_chunked`. Thanks as always for your help!
