### ISSUE TITLE
Features Should Denote More Granular Subscription Tier

### ISSUE THREAD

**Issue by DSCourcy** [elastic/docs#1702]
It would be useful if, for a given feature, the subscription tier was listed in documentation.

For example, consider: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-pinned-query.html

The "x-pack" icon tells me that this is under Elastic license - but I have no sense for: is it Basic / Gold / Platinum / Enterprise?

cc: @gingerwizard @zuketo

**Comment by lcawl** [comment]
If you click that "x-pack" icon, it takes you to the Subscriptions page, which is our source of truth.

**Comment by debadair** [comment]
This is information that we want to maintain in a single location. It is important from a licensing standpoint that it is correct, and maintaining granular subscription level information in the docs would spread the information across many books and repos.
