### ISSUE TITLE
Add an HTML anchor <a> with the digest of the code example

### ISSUE THREAD

**Issue by ezimuel** [elastic/docs#1709]
This is a proposal to add an HTML anchor `<a name="36818c6d9f434d387819c30bd9addb14">` with the digest of the code examples in the [Elasticsearch Reference](https://www.elastic.co/guide/en/elasticsearch/reference/master/index.html) documentation.

![anchor_example_digest](https://user-images.githubusercontent.com/475967/73077006-93594c00-3ebf-11ea-9a84-882536cda96e.png)

Right now, it's very difficult to find the location of a code example in the documentation. We have this [alternatives_report.json](https://raw.githubusercontent.com/elastic/built-docs/master/raw/en/elasticsearch/reference/master/alternatives_report.json) file that contains all the console examples with page names and digests. We can find the documentation page where the example is present but we need to scroll manually and comparing the code content with the one reported on the page. Not that easy!

Having this HTML anchor based on the digest we can simplify all the process and share code examples in the Elasticsearch documentation with just a link, e.g. https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-index_.html#36818c6d9f434d387819c30bd9addb14

I'm pretty sure that the digest is already managed by the script that converts Asciidoc to HTML. We need to add a `<a name="digest-value">` before the code example.

CC @elastic/es-clients-core

**Comment by debadair** [comment]
The doc build uses the digest to look up and inject the client examples, so it shouldn't be hard to also add an anchor. 

https://github.com/elastic/docs/tree/master/resources/asciidoctor/lib/alternative_language_lookup

**Comment by ezimuel** [comment]
Thanks @nik9000 for https://github.com/elastic/docs/pull/1717
