### ISSUE TITLE
Fix doc for Cloud Enterprise Documentation / Planning your installation - Prerequisites - Software

### ISSUE THREAD

**Issue by alaa-mallah** [elastic/docs#1723]
URL referring where doc fix is required:
https://www.elastic.co/guide/en/cloud-enterprise/current/ece-prereqs-software.html

On below line from our doc
Red Hat Enterprise Linux 7 or **later** (RHEL 7), Limitations | 1.131

Per our support matrix we support RHEL 7 but above line can be interpreted that we support Redhat 7 or later which might be interpreted as version 8 as well

**Comment by alaudazzi** [comment]
Fixed in [#51144](https://github.com/elastic/cloud/pull/51144).
