### ISSUE TITLE
Kibana settings documentation overlays right navigation menu

### ISSUE THREAD

**Issue by bahaaldine** [elastic/docs#173]
https://www.elastic.co/guide/en/kibana/current/settings.html

On chrome Version 58.0.3029.81 (64-bit)

![capture d ecran 2017-04-28 a 16 27 10](https://cloud.githubusercontent.com/assets/820299/25533099/cc3a21a2-2c2f-11e7-866f-1a386c9b7943.png)

**Comment by gtback** [comment]
Probably related to #148. Either way, this doesn't seem to be a problem anymore.
