### ISSUE TITLE
There's no link from the 7.5 version pages to the equivalent 7.6 version pages

### ISSUE THREAD

**Issue by debadair** [elastic/docs#1743]
From @monfera 

![image](https://user-images.githubusercontent.com/362578/75081377-cfce9680-54c3-11ea-9efb-cca344a4438b.png)

I click "current release documentation" and it lands me on 7.6... but it's the ToC. This issue has persisted for years and may diminish from the image of our product quality to an extent I'm not qualified to judge.

Note: This was originally opened against our search implementation, but it's a docs issue.

**Comment by debadair** [comment]
The banners are standard boilerplate that's inserted automatically on each page by the doc build. The "current release documentation" link is relative to the book, but is not "page aware". 

The version picker *is* page aware and enables users to flip to the same page in the current version, if it exists. 

Depending on how we handle this messaging in the new design, we could either make the links page aware, or remove them and direct the reader to switch versions using the standard mechanism. (Redundant navigation elements aren't necessarily a desirable thing...)

**Comment by debadair** [comment]
Leaving this open as improving the user experience here is related to improving our management of redirects (#1820).

**Comment by gtback** [comment]
Each version of each book (for example, the 7.5 Elasticsearch Reference and the 7.6 Elasticsearch Reference) are built independently, so there's currently no way for one page to know that the other versions have an equivalent page, at build time. The version dropdown is smart enough to figure out when the equivalent page exists or not, so it should be pretty straightforward to make the banner at the top do the same thing.

**Comment by gtback** [comment]
Closing this in favor of #2109
