### ISSUE TITLE
Typo in "Chunking in the right place" section

### ISSUE THREAD

**Issue by HermitStudio** [elastic/docs#1750]
I noticed a small typo when reading the "Chunking in the right place" section.

In the line:

> However, for **mot** of our books, this results in enormous pages.

I assume "mot" should be "most".

FYI: My name is Corrie Allan :)

**Comment by alaudazzi** [comment]
@HermitStudio can you provide the HTML page where you noticed the typo?

**Comment by gtback** [comment]
Thanks for pointing this out @HermitStudio
