### ISSUE TITLE
Typo in "Adding new docs or new branches" chapter

### ISSUE THREAD

**Issue by HermitStudio** [elastic/docs#1751]
I saw a typo on the "Adding new docs or new branches" chapter.

In the line:

> When we fork a branch **like like** 7.x or 7.9 we typically add it to the list of branches so we immediately start building docs for it while we’re actively developing against it.

I assume we can drop one "like".

Corrie

**Comment by alaudazzi** [comment]
@HermitStudio can you provide the relevant HTML page?

**Comment by gtback** [comment]
Thanks for pointing this out @HermitStudio
