### ISSUE TITLE
Link example describes the link text incorrectly

### ISSUE THREAD

**Issue by HermitStudio** [elastic/docs#1752]
On the chapter: guide/linking.html aka "Linking," the section "Internal links" has the following sentence: 

> It will use the title associated with each ID as the link text. In the example above, note-id is not associated with any title, which is why the text is rendered as **"Note"**.

However, in the bullet of links above this sentence, the note-id link text is "Linking:"

<img width="768" alt="Screen Shot 2020-02-26 at 13 08 50" src="https://user-images.githubusercontent.com/3171101/75343658-39bab780-5899-11ea-8423-e6a846c73057.png">

The sentence should reflect the correct link name.

**Note**: I noticed this in my local build with the latest changes from the repo. I'm not sure if that affects the way the link is handled/rendered.

Corrie

**Comment by gtback** [comment]
I actually don't know if this is true anymore in AsciiDoctor, so I'm just going to remove that sentence. Thanks @HermitStudio.
