### ISSUE TITLE
Incorrect indentation in "Bullet points" section

### ISSUE THREAD

**Issue by HermitStudio** [elastic/docs#1753]
In the "Lists" chapter (guide/lists.html), there in an incorrect indentation in the rendered example.

In the code you have:

```
** Sub-point
*** Sub-sub-point
```

However, in the rendered example both sub-points appear on the same indentation level and they both have the same name (the last bullet should be "Sub-sub-point"):

<img width="778" alt="Screen Shot 2020-02-26 at 13 22 53" src="https://user-images.githubusercontent.com/3171101/75344720-80a9ac80-589b-11ea-8164-563607adb023.png">

**Comment by gtback** [comment]
Thanks for pointing this out @HermitStudio
