### ISSUE TITLE
[DOCS] Enable support for mathematical formulae in docs

### ISSUE THREAD

**Issue by szabosteve** [elastic/docs#1765]
At the moment, mathematical formulae added in Asciidoc are not rendered correctly in the HTML output.

For example, `sum_(i=1)^n i^3=((n(n+1))/2)^2` is rendered as you can see here:
<img width="197" alt="Screenshot 2020-03-06 at 9 00 31" src="https://user-images.githubusercontent.com/22324794/76063989-14a90180-5f89-11ea-996b-82ee572847b1.png">

instead of this:
<img width="183" alt="Screenshot 2020-03-06 at 9 03 46" src="https://user-images.githubusercontent.com/22324794/76064179-6e113080-5f89-11ea-94d7-9c625fe95542.png">

It would be nice to support these formulae in Asciidoc as sometimes they would be really helpful in explaining a function. Something like AsciiMath markup might be a way to enable that.

**Comment by gtback** [comment]
@szabosteve It seems like Asciidotor supports this [out of the box] (https://asciidoctor.org/docs/user-manual/#stem). Is that not working (meaning there might be something elsewhere in our build process that breaks it)?

**Comment by szabosteve** [comment]
@gtback 

Thank you for looking into it. I just tried it again with both the [AsciiMathML](http://asciidoc.org/asciimathml.html) and the [LaTeXMathML](http://asciidoc.org/latexmathml.html) notation and none of them worked. I used the `asciimath:[]` and the `latexmath:[]` in-line macros as the documentation suggests. Am I missing something?

Maybe it is not relevant but I also noticed that the documentation pages of the MathMLs that I linked above do not render the source input correctly. The list of example formulae is just not looking the way that it should be.

For example, [on AsciiMathML](http://asciidoc.org/asciimathml.html) the last example formula according to the AsciiDoc source is: `asciimath:[x^2+y_1+z_12^34]`
But it is rendered this way:
<img width="105" alt="Screenshot 2020-05-13 at 8 55 16" src="https://user-images.githubusercontent.com/22324794/81780884-8bb5c580-94f7-11ea-9f23-cb950f95a1d0.png">
Which is clearly incorrect. So it seems to me that it is broken even on its own documentation site. Just wanted to highlight it, maybe it is relevant/helpful.

**Comment by gtback** [comment]
@szabosteve I was able to get this to work by adding the `stem` attribute at the top the README.asciidoc (so for your case, you could put it in index.asciidoc in whichever book you're working on).

```adoc
= Docs HOWTO
:stem:
```

and then adding this to the body:

```adoc
== Conditions of use

stem:[sum_(i=1)^n i^3=((n(n+1))/2)^2]
```

For a centered block you can use:

```adoc
[stem]
++++
x/x={(1,if x!=0),(text{undefined},if x=0):}
++++
```

All of this does rely on the docs being able to load external JavaScript (I think from mathjax.org).

Let me know if you have any problems.

**Comment by szabosteve** [comment]
@gtback 

Thank you for your help! I added the `stem` attribute to the index.asciidoc file, and it seems it did the magic and now the formulae are rendered correctly.

Thanks again for looking into it!

**Comment by gtback** [comment]
Happy to help @szabosteve !
