### ISSUE TITLE
--resource [path] recognized as relative path when building Elasticsearch docs in doc_build_aliases.sh

### ISSUE THREAD

**Issue by jureaky** [elastic/docs#1767]
**OS: Ubuntu 18.04**
**Elasticsearch version: master**

I tried to build Elasticsearch docs using the `docbldes` alias made in `doc_build_aliases.sh`.
I set **$GIT_HOME=/home/juhan**, which is my home directory.
The problem is `--resource` option recognizes the given path as a relative path.
Therefore the command only worked when I executed in the directory which contains `elasticsearch` directory.

Here is error message when I executed in one of subdirectories of elasticsearch:
```
juhan@VM-OSC-1:~/osc/elasticsearch/docs/reference$ docbldes
Can't find --resource /home/juhan/osc/elasticsearch/docs/reference/elasticsearch/x-pack/docs
```

**Comment by lcawl** [comment]
I think what you describe is expected behaviour.  Please see the comment about setting $GIT_HOME in https://github.com/elastic/docs/blob/master/doc_build_aliases.sh:

> ...set the $GIT_HOME variable to the directory that contains your local copies of the elastic repos...

**Comment by jureaky** [comment]
Thank you for your reply. 
I think it was just a temporary error. Now it works well in any directory ! :)

**Comment by jureaky** [comment]
just FYI, the link `https://github.com/elastic/x-pack/blob/master/README.md` in the comment about setting $GIT_HOME in https://github.com/elastic/docs/blob/master/doc_build_aliases.sh is broken.

**Comment by lcawl** [comment]
Thanks, I've removed that link via https://github.com/elastic/docs/pull/1771
