### ISSUE TITLE
Preview link for doc build results in a 404

### ISSUE THREAD

**Issue by jrodewig** [elastic/docs#1793]
The PR for elastic/elasticsearch#54581 never generated a functioning doc preview link. Instead, the preview links resulted in a 404 page.

**Jenkins console output**
https://elasticsearch-ci.elastic.co/job/elastic+docs+elasticsearch+pull-request/20218/console

**Preview link**
http://elasticsearch_54581.docs-preview.app.elstc.co/diff

As a note, this PR targeted a feature branch. However, that hasn't impacted preview generation in the past.

**Comment by lcawl** [comment]
Same is true for https://github.com/elastic/kibana/pull/65591

**Comment by gtback** [comment]
> Same is true for elastic/kibana#65591

This one resulted in a `INFO:build_docs:No changes to push` (perhaps because everything in that PR is commented out?)

**Comment by lcawl** [comment]
You're right, nevermind!  No other pages are using those tagged sections yet, so they wouldn't pick up those changes.

**Comment by gtback** [comment]
@jrodewig It looks like that build has expired (or at least, it's not coming up for me), probably because it's more than a month old. I'm going to close this, but feel free to reopen it if there's another time this happens, or just make a new GitHub issue.

Sorry for not noticing this at the time.
