### ISSUE TITLE
Support glob matching for the `include` directive

### ISSUE THREAD

**Issue by jrodewig** [elastic/docs#1816]
Currently, the Asciidoctor `include` directive does not support [glob matching](https://en.wikipedia.org/wiki/Glob_(programming)) for filepaths. However, there are frequently cases in which we want to include _all_ Asciidoc files in a directory.

### Example

In the [`master` branch of the Elastic Installation and Upgrade Guide](https://github.com/elastic/stack-docs/edit/master/docs/en/install-upgrade/breaking.asciidoc), the `include` directive is used to pull in breaking changes from the ES reference guide:

```
include::{es-repo-dir}/reference/migration/migrate_8_0.asciidoc[tag=notable-breaking-changes]
include::{es-repo-dir}/reference/migration/migrate_8_0/analysis.asciidoc[tag=notable-breaking-changes]
include::{es-repo-dir}/reference/migration/migrate_8_0/discovery.asciidoc[tag=notable-breaking-changes]
include::{es-repo-dir}/reference/migration/migrate_8_0/http.asciidoc[tag=notable-breaking-changes]
include::{es-repo-dir}/reference/migration/migrate_8_0/ilm.asciidoc[tag=notable-breaking-changes]
include::{es-repo-dir}/reference/migration/migrate_8_0/java.asciidoc[tag=notable-breaking-changes]
include::{es-repo-dir}/reference/migration/migrate_8_0/mappings.asciidoc[tag=notable-breaking-changes]
include::{es-repo-dir}/reference/migration/migrate_8_0/network.asciidoc[tag=notable-breaking-changes]
include::{es-repo-dir}/reference/migration/migrate_8_0/packaging.asciidoc[tag=notable-breaking-changes]
include::{es-repo-dir}/reference/migration/migrate_8_0/security.asciidoc[tag=notable-breaking-changes]
include::{es-repo-dir}/reference/migration/migrate_8_0/snapshots.asciidoc[tag=notable-breaking-changes]
include::{es-repo-dir}/reference/migration/migrate_8_0/transport.asciidoc[tag=notable-breaking-changes]
```

While this works, it's prone to error. Updaters in the ES reference may forget to add an `include` directive in the Install and Upgrade guide, which is housed in a separate repo.

If glob matching were supported, the above code could be replaced with:

```
include::{es-repo-dir}/reference/migration/migrate_8_0/*.asciidoc[tag=notable-breaking-changes]
```

Updaters in the ES reference wouldn't need to worry about the Install and Upgrade Guide. It would just work!

### Proposal
While not supported natively, Asciidoctor does offer a [glob include processor extension](https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/glob-include-processor.rb). We could add this processor to the docs build to support glob matching.

**Comment by gtback** [comment]
@jrodewig would you want the files to be included in lexicographic order by filename? If so, this would be pretty easy to incorporate. Otherwise, we'd have to look for a more expressive way to indicate the order (or hope that they get globbed in the same order we want).

**Comment by jrodewig** [comment]
@gtback Lexographic order makes sense to me. In cases where people want a specific, non-lexographic order, it probably makes sense to just maintain a curated list of includes.

**Comment by gtback** [comment]
Sounds good!

**Comment by gtback** [comment]
This is probably distinct from #324, but they're similar enough that I at least wanted to link the two together.

**Comment by gtback** [comment]
I just ran across [this extension](https://puravida-asciidoctor.gitlab.io/asciidoctor-extensions/#_each_file) which might be more complex than necessary, but would likely do what we need.

**Comment by jrodewig** [comment]
This is no longer a priority now that development of a new docs system is underway. Closing this issue.
