### ISSUE TITLE
Update elasticsearch-ci/docs to do a full rebuild in the docs repo

### ISSUE THREAD

**Issue by bmorelli25** [elastic/docs#1821]
Cross document links between differently versioned books are too easy to break at release time. I did in the APM repos during the 7.6 release, and it's happening right now with the ECK 1.1 release.

A potential solution would be to change the `elasticsearch-ci/docs` check, in this repo only, to default to a full rebuild: `@elasticmachine, run elasticsearch-ci/docs rebuild`. This change will ensure that cross-document links are always checked.

**Comment by nrichers** [comment]
@gtback just to add a bit of context: Even if the full builds require more hardware resources or will take longer, NOT having these things break on release days with a simple build change would be very beneficial. 

For the ECK 1.1 release, at least four people ended up spending time on this problem and I lost the better part of half a day from it*, not to mention the added stress that comes from breaking the docs. Running a full docs build on elastic/docs PRs is cheap in comparison.

*Fixing links shouldn't ever take half a day, but if you throw in persistent Jenkins issues in the cloud-on-k8s repo that were slowing down the link fixes, it can end up taking that long. It. was. painful.

**Comment by gtback** [comment]
It seems like there's an underlying problem with not doing full cross-book link checking when the "current" version of a book changes. Doing full rebuilds for every PR to this repo would be an intermediate solution (which would cause links to get checked), but I'd also like to fix the underlying problem.
