### ISSUE TITLE
Add (first release) in nav, similar to (current)

### ISSUE THREAD

**Issue by kurtado** [elastic/docs#183]
Just a thought, while browsing the docs, and trying to figure out the first version in which a feature hit... It would be nice if that dropdown offered something like `(released)`, similar to the way we automagically label the `(current)` release.

**Comment by clintongormley** [comment]
There's no way we could do this reliably without doing it manually, which would mean enormous overhead.

**Comment by kurtado** [comment]
ok thanks :)
