### ISSUE TITLE
Allow custom docs landing page

### ISSUE THREAD

**Issue by gchaps** [elastic/docs#1892]
Instead of having a docs landing page with a [long link farm](https://www.elastic.co/guide/en/kibana/current/index.html)&mdash;which is difficult to scan,&mdash;we'd like create a custom landing page similar to the image below.  It would be nice if we could also add images to the landing page.

See this draft PR:
[https://github.com/elastic/kibana/pull/71537](https://github.com/elastic/kibana/pull/71537)

<img width="697" alt="Screen Shot 2020-07-13 at 11 12 13 AM" src="https://user-images.githubusercontent.com/33642766/87352376-ca73f600-c50f-11ea-807b-1e77db2b919d.png">

See this draft PR:
[https://github.com/elastic/kibana/pull/71537](https://github.com/elastic/kibana/pull/71537)

**Comment by gtback** [comment]
This should be working now, so I'll close this, but we can re-open if needed.
