### ISSUE TITLE
Incorrect parameter 'collect' instead of 'collect_mode' on 'Preventing Combinatorial Explosions'

### ISSUE THREAD

**Issue by 36degrees** [elastic/docs#19]
On the guide page '[Preventing Combinatorial Explosions](https://www.elastic.co/guide/en/elasticsearch/guide/current/_preventing_combinatorial_explosions.html#_depth_first_versus_breadth_first)' under figure 48 it states

> To use breadth-first, simply enable it via the `collect` parameter:

I believe this should instead say

> To use breadth-first, simply enable it via the `collect_mode` parameter:

**Comment by clintongormley** [comment]
This issue was moved to elastic/elasticsearch-definitive-guide#390

**Comment by 36degrees** [comment]
Ahah! That explains why I couldn't find it in the source. Thanks, @clintongormley.
