### ISSUE TITLE
fatal: cannot create directory at 'html/en/x-pack/5.4/:images': Invalid argument

### ISSUE THREAD

**Issue by fengquan8866** [elastic/docs#190]
windows10
docs/html/en/x-pack/5.4/:images

run:  git reset --hard

fatal: cannot create directory at 'html/en/x-pack/5.4/:images': Invalid argument
![_20170603170918](https://cloud.githubusercontent.com/assets/13045390/26752308/78afec12-487f-11e7-8113-c9ea1c3d9b55.png)

**Comment by clintongormley** [comment]
thanks - fixed
