### ISSUE TITLE
7.9 Provide custom banner text for the SIEM and Security docs

### ISSUE THREAD

**Issue by benskelker** [elastic/docs#1905]
To try and help users know which docs they need, let's add some info the preliminary and previous doc releases.

On 7.9 Security doc pages, add this banner:

The SIEM app is now a part of the Elastic Security solution. [Click here](https://www.elastic.co/guide/en/siem/guide/7.8/index.html) to view SIEM documentation for previous releases.

For 7.8 and below SIEM doc pages, add this banner:

The SIEM app is now a part of the Elastic Security solution. [Click here](https://www.elastic.co/guide/en/security/current/index.html) to view the current documentation. IMPORTANT: No additional bug fixes or documentation updates will be released for this version.

**Comment by benskelker** [comment]
@gtback - I think I resolved this locally, in the stack-docs and security-docs repos:

- stack-docs PR: https://github.com/elastic/stack-docs/pull/1344
- security-docs PR: https://github.com/elastic/security-docs/pull/197

I'd appreciate if you can check everything is OK.

Thanks

**Comment by gtback** [comment]
For the `stack-docs` PR, it seems like all versions prior to 7.8 have the default "see the current release documentation" message that points to 7.8, and then 7.8 has the custom header to point to the new Security Guide. I think this is fine, even though it's one extra click (compared to directly going from 7.2 to 7.9) for people looking at old versions of the docs. It's not worth backporting to all the older branches. 

For the security-docs changes, these will only show on the 7.9 docs (which are currently the "current" version), not 7.x or master branches (which have their own "preliminary documentation for a future release" banner). I also think this is fine, as long as we remember to add the file when we cut the 7.10 branch, or we decide we don't want to keep showing the banner past 7.9.
