### ISSUE TITLE
Add paths to Kibana docs

### ISSUE THREAD

**Issue by gtback** [elastic/docs#1917]
This was originally done in #1904 but reverted in 415efb1fc0fe5c9ce75242fc86b518132df31560. See if we can reproduce the issue and get this merged in.

**Comment by stacey-gammon** [comment]
Blocking https://github.com/elastic/kibana/pull/72292

**Comment by gtback** [comment]
Since elastic/kibana#72292 is now passing the docs build, and I haven't the [Kibana PR Docs builds](https://elasticsearch-ci.elastic.co/job/elastic+kibana+pull-request+build-docs/) all seem to be passing recently (when they were failing before), I'm going to close this issue. I'll reopen if there's more weirdness.
