### ISSUE TITLE
Missing link on Installing X-Pack page?

### ISSUE THREAD

**Issue by cdahlqvist** [elastic/docs#194]
It looks like the 'Install X-Pack' page [1] does not contain a link to the instructions for how to set up monitoring for Logstash [2]. It seems like this is required whenever there is no local Elasticsearch instance (which is what the config defaults to). Is this an issue or by design?

[1] https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html
[2] https://www.elastic.co/guide/en/x-pack/current/monitoring-logstash.html

**Comment by clintongormley** [comment]
@cdahlqvist please open this on the x-pack repo, not here
