### ISSUE TITLE
Recommended way of setting title abbreviations does not work.

### ISSUE THREAD

**Issue by dedemorton** [elastic/docs#1959]
The [docs readme](https://github.com/elastic/docs/blob/master/README.asciidoc#toc-titles) shows 2 ways to set a title abbreviation. The first way is recommended, but doesn't work. The passthru block does work, so I'll continue to use it. If we don't plan to support the first way, the readme needs to be updated.

![image](https://user-images.githubusercontent.com/14206422/93412383-eb2f3380-f851-11ea-9749-0aea0fc0eb46.png)

**Comment by gtback** [comment]
I started looking into the history of this. It looks like it was originally added in #1524 and later modified (possibly breaking it) in #1539. 

I definitely prefer the section attribute approach if we can get it to work, but realistically we won't be removing support for the other way, either.

**Comment by dedemorton** [comment]
I don't know if this is still a problem, but I'm closing this issue because the passthru blocks work just fine.
