### ISSUE TITLE
Reorganize the documentation guide page with solutions up top

### ISSUE THREAD

**Issue by DanRoscigno** [elastic/docs#1988]
I think that having the solutions up top would be better for customers.  By moving the solution guides to the top the customers will find the new content first.  https://www.elastic.co/guide/index.html

Suggestion (just top level headings shown):

Observability: APM, Logs, Metrics, and Uptime

Elastic Security

Enterprise Search

Cloud: Provision, Manage and Monitor the Elastic Stack

Elastic Stack

Elasticsearch: Store, Search, and Analyze

Kibana: Explore, Visualize, and Share

Beats: Collect, Parse, and Ship

Logstash: Collect, Enrich, and Transport

Docs in Your Native Tongue

Legacy Documentation

cc: @gtback

**Comment by gtback** [comment]
Thanks for the suggestion, @DanRoscigno. I know there are some efforts around re-architecting a lot of the content, but on the other hand, moving things around on the page might make it harder for people who are used to where they are now. 

I'm curious what the rest of the @elastic/docs writers think.

**Comment by dedemorton** [comment]
IMO the page is not currently organized in any logical order right now, so I would not expect users to rely on the structure. They'll search and find what they need.

I agree with @DanRoscigno that putting the observability info at the top of the page is the right thing to do if we want to place focus on our solutions.

I might be a bit biased, though, so let's hear from the rest of the team!

**Comment by gtback** [comment]
I haven't run the stats, but I'm curious how much of our traffic actually comes through this page vs. people having pages bookmarked or coming in from search results. **I** look at the home page a lot, but my role almost certainly makes me an exception.

**Comment by dedemorton** [comment]
I looked at google analytics, and it looks like /guide/ gets quite a lot of traffic. I think people use it for navigation because it's hard to move between related books right now.

**Comment by DanRoscigno** [comment]
Closed by new solution based docs moving to /docs page
