### ISSUE TITLE
typo in documentation

### ISSUE THREAD

**Issue by rmetzler** [elastic/docs#2063]
I'm sorry, I can't find the source file for the document I'm referring to and therefore I couldn't create a pull request to fix this documentation issue.

In the table at https://www.elastic.co/guide/en/app-search/current/documents.html#documents-post-and-patch there is a row **"JSON must be an array or hash"**

The documentation has a typo with the urlencoding for `[]`, which is `%5B%5D`. The documentation says it should be `%5D%5B`.

The proposed change is as follows:

```diff
- If you are using query parameters, ensure that ids is followed with %5D%5B - this is an array, but escaped: ?ids%5D%5B=.
+ If you are using query parameters, ensure that ids is followed with [] - this is an array, but urlencoded: ?ids%5B%5D=.
```

**Comment by gtback** [comment]
Hi @rmetzler, this has been updated. Thanks again for pointing it out!
