### ISSUE TITLE
Wrap long setting names at dots (when they appear in a table cell)

### ISSUE THREAD

**Issue by dedemorton** [elastic/docs#2077]
The observability docs team wants to provide the best possible user experience with our docs, so we plan to follow the Kibana doc team's lead and use tables to format our settings reference info.

Currently the column width in some tables is made unnaturally wide by the presence of one or two long fields. This results in a table that is not fully visible (users need to scroll to the right to see the full text of the right column).

To mitigate this issue right now, we need to manually wrap setting names. It would be better if the doc build could do that for us. Not sure if that's possible, but you can see by looking at [docs from other companies](https://cloud.google.com/appengine/docs/standard/go111/config/appref) that it provides a much better user experience.

Here you can see a problem with one of our tables:

![image](https://user-images.githubusercontent.com/14206422/110011229-0abcfa00-7cd4-11eb-98fa-835bb445b2b3.png)

**Comment by gtback** [comment]
It looks like there's a `<wbr>` [HTML element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr) that could be used for this, which we could put in any settings without worrying about causing too many breaks. Based on my testing, it does break the "double-click to select the whole name" workflow, but that's likely not a major problem.

A couple questions @dedemorton: 
1. Do you have a link to a page with this problem to make it easier for me to test any changes?
2. Is this important enough that it should be done in the current docs system, and not wait for the redesign?

**Comment by dedemorton** [comment]
1. There's a good example in this table, but it's a draft PR: https://observability-docs_424.docs-preview.app.elstc.co/guide/en/fleet/master/elastic-agent-input-settings.html#input-container-data-manipulation-settings (see the publisher_pipeline.disable_host setting). I pushed a new commit this morning, and the page is no longer showing a scrollbar below the table, but you can see that the right col is still too narrow. 

2. I think this is important enough that we shouldn't wait for the new docs system. Kibana is already using tables extensively, and we will be using them for agent starting in 7.12.

If we can't set up some kind of rule (wrap at a . or _ for settings over n characters), then I think having the author manually control the wraps is OK. The only problem with manual wraps is that we'll need to automate the creation of reference content at some point. I think the logic for deciding how content wraps in the rendered page should live in the docs system and not the source files and/or scripts that will eventually generate those files.

**Comment by dedemorton** [comment]
Part of the issue at play here, too, is that we simply don't allow enough text on a line in the rendered docs. If you look at the app engine docs that I shared earlier, you can see that one line of text allows for more characters, yet the smaller font is still perfectly readable.

https://cloud.google.com/appengine/docs/flexible/java/reference/app-yaml

**Comment by dedemorton** [comment]
Closing because this issue is quite old. If this work is still required, please open a new issue.
