### ISSUE TITLE
Admonitions within a table are cut off

### ISSUE THREAD

**Issue by lcawl** [elastic/docs#2096]
In https://github.com/elastic/kibana/pull/95847 I added [admonitions](https://github.com/elastic/docs#additions-and-deprecations) for the deprecated settings in a table (in particular, on this page: https://www.elastic.co/guide/en/kibana/master/reporting-settings-kb.html). It seems that the pop-ups are cut off at the border of the table. For example:

![image](https://user-images.githubusercontent.com/26471269/113199344-de859200-921b-11eb-9a3e-4d5657003288.png)

Likewise, the same problem occurs if you have description lists that use the "horizontal" style attribute (as described in https://docs.asciidoctor.org/asciidoc/latest/lists/description/) In https://www.elastic.co/guide/en/kibana/master/advanced-options.html, for example: 

![image](https://user-images.githubusercontent.com/26471269/113063791-b9851680-916a-11eb-8ec6-d7e8e7e488bc.png)

Hopefully we can avoid all these formatting issues by using a custom component for settings reference pages in the new docs system. Then we'll just need to ensure it supports deprecation admonitions or deprecation tags/labels.

**Comment by lcawl** [comment]
I misspoke--these aren't tables, they're description lists that use the "horizontal" style attribute (as described in https://docs.asciidoctor.org/asciidoc/latest/lists/description/).  Hopefully we can avoid all these formatting issues by using a custom component for settings reference.  Then we'll just need to ensure it supports deprecation admonitions or deprecation tags/labels.

**Comment by gtback** [comment]
I think this is the same thing as #1754?

**Comment by lcawl** [comment]
Closing as duplicate of https://github.com/elastic/docs/issues/1754
