### ISSUE TITLE
Support Builds on Apple M1 machines

### ISSUE THREAD

**Issue by gtback** [elastic/docs#2158]
It's currently not possible to build the Docker image(s) on M1 mac machines. This issue will cover intermediate workarounds and also track long-term progress towards making this work.

**Comment by gtback** [comment]
See https://github.com/elastic/docs/tree/m1-workaround#what-is-this-branch for documentation on the current workaround.

**Comment by gtback** [comment]
@seanstory I think you've run into this problem before. Can you try the workaround above and see if it works for you?

**Comment by seanstory** [comment]
@gtback I tried:
```
./build_docs --doc README.asciidoc
source doc_build_aliases.sh  # to get access to the docserve command
docserve
```

And it started up without issue, but the styling looks very off.

<img width="1427" alt="Screen Shot 2021-07-26 at 11 59 25 AM" src="https://user-images.githubusercontent.com/5288246/127029159-3e371823-4bb4-486d-a0ad-fb98e7b80f9a.png">


Did I miss a step or anything?

**Comment by gtback** [comment]
@seanstory That's what it looks like when the static assets (JavaScript, CSS, etc.) can't be loaded. The alias should have handled that:

https://github.com/elastic/docs/commit/40d87e0aa89828580ea93d09c83a7791d0855ab0#diff-607b0d67404c93093e1c474b8e1abb4a9ae5498ab18675e96b1f5621cc822f79R251

Can you double-check that you have files in the `workaround-static` directory? If not, let me know and I can look into it. If so, can you check in DevTools about where it's trying to load the files from and if it can find them?

If you're still having problems, ping me and we can figure it out together.

**Comment by gtback** [comment]
Closing since #2280 was merged
