### ISSUE TITLE
The `Uses lucene query syntax` link in Kibana - Discover search bar is broken.

### ISSUE THREAD

**Issue by nguyenlp** [elastic/docs#217]
In Kibana, the `Uses lucene query syntax` link in Kibana --> Discover search bar is broken.

The link that is displayed in the search bar in the Discover section is broken. It references: 

https://www.elastic.co/guide/en/elasticsearch/reference/5.x/query-dsl-query-string-query.html#query-string-syntax 

However the part that is broken is "...reference/5.x/..." - there is no 5.x (anymore), the correct link is: 

https://www.elastic.co/guide/en/elasticsearch/reference/5.5/query-dsl-simple-query-string-query.html
Yesterday at 3:37 PM

Please see attachment -  `Uses lucene query syntax` link on top right corner in search bar:

![screen shot 2017-07-27 at 10 35 22 am](https://user-images.githubusercontent.com/6330504/28675994-760ff1e8-72b7-11e7-82d8-4aab28d6a42f.png)

Click that `Uses lucene query syntax` link takes you to a 404 page error.

![screen shot 2017-07-27 at 10 05 30 am](https://user-images.githubusercontent.com/6330504/28674402-4a85e478-72b3-11e7-8627-280a8bb2198a.png)

**Comment by clintongormley** [comment]
Please open this issue on the Kibana repo instead
