### ISSUE TITLE
build_docs.pl does not generate HTML documentation that works in offline environments

### ISSUE THREAD

**Issue by lcawl** [elastic/docs#218]
The documentation generated by build_docs.pl contains links to images, CSS, and JS files on elastic.co (specifically in the header of the output files), which is not ideal for users who want to view the information offline. 

Though there is an option for generating PDF files, we should have an option for generating individual offline HTML docs too.  

Cross-book links (which are implemented as external links) would not work, but just being able to view the HTML with the CSS and Javascript working as designed would be a huge improvement. 

One option might be to investigate adding the a2x --stylesheet parameter.

**Comment by debadair** [comment]
Fixed by the Docker-based air-gapped docs. #1223
