### ISSUE TITLE
Elastic Guide not searchable | 7.15/current docs re-crawl

### ISSUE THREAD

**Issue by stefnestor** [elastic/docs#2227]
All [Elastic Guide](https://www.elastic.co/guide/index.html) docs on `current` or `7.15` version are not searchable. The pages are currently being re-crawled to make search results available. 

**Workaround**
In the mean time, kindly switch documentation to version `7.14` to be able to search or use a Google search as exemplified below.

**Symptom**

Can search Google for results, but not use Elastic search.

![image](https://user-images.githubusercontent.com/26751266/134703928-b572d194-7049-44ec-aab9-33b8fccd9041.png)

Attempting search will give generic first page (though result will look like it has a desired hit)

![image](https://user-images.githubusercontent.com/26751266/134704272-3b24f46f-d372-4139-96a1-4259b56a1655.png)

**Related**
- https://github.com/elastic/docs/pull/2226

**Comment by goodroot** [comment]
Thanks to sleuthing from @mikeisonthenets we found out that Varnish is sending a 403 to crawl attempts:

<img width="448" alt="Screen Shot 2021-09-24 at 10 44 26 AM" src="https://user-images.githubusercontent.com/9484709/134722023-b7c95bea-8c5c-4488-b8bc-81c7b9790db1.png">

The pages themselves are fine and do not indicate an issue:

* Sitemaps are current and correct.
* There are no misaligned `noindex` attributes.
* The crawler is "doing what it is supposed to do".
* `/current/` urls direct to 7.15 as expected.

**Comment by goodroot** [comment]
Investigated and on the way to closure here: https://github.com/elastic/website-development/issues/8219

Thanks for the report. 👍
