### ISSUE TITLE
Links in painless API Docs are broken.

### ISSUE THREAD

**Issue by Xylakant** [elastic/docs#223]
The links in the painless API reference at https://www.elastic.co/guide/en/elasticsearch/painless/5.5/painless-api-reference.html#painless-api-reference are broken, for example arcDistance links to https://artifacts.elastic.co/javadoc/org/elasticsearch/elasticsearch/5.5.1/org/elasticsearch/index/fielddata/ScriptDocValues$GeoPoints.html#arcDistance%2Ddouble%2Ddouble%2D which 404s

**Comment by clintongormley** [comment]
@nik9000 There is a disconnect between the javadoc links and the files, eg the link has `ScriptDocValues$GeoPoints.html` while the file is `ScriptDocValues.GeoPoints.html`

This link works: https://artifacts.elastic.co/javadoc/org/elasticsearch/elasticsearch/5.5.1/org/elasticsearch/index/fielddata/ScriptDocValues.GeoPoints.html#arcDistance%2Ddouble%2Ddouble%2D

**Comment by nik9000** [comment]
I pushed https://github.com/elastic/elasticsearch/commit/b840fa31171708bd354e2625a91e7530ddfe0f4b, https://github.com/elastic/elasticsearch/commit/d28a14ba14e079b452aea3299e744900d1d7cff1, https://github.com/elastic/elasticsearch/commit/4e2ed0d7283d07531d4bc23b0ab22d43cbaa9342, https://github.com/elastic/elasticsearch/commit/26aefac279d8c6f904d1cc6bc7cba526b960c02f, and https://github.com/elastic/elasticsearch/commit/57ab021ca6f13d069b01e79ec713f6c98a4a5362 to fix this in master, 6.x, 6.0, 5.6, and 5.5.

**Comment by nik9000** [comment]
I believe the links should be fixed on the site in the next half an hour.
