### ISSUE TITLE
documentation missing for APM view of the new comparison feature

### ISSUE THREAD

**Issue by 111andre111** [elastic/docs#2268]
As of today we don't unfortunately document the new comparison feature in our kibana documentation:
https://github.com/elastic/kibana/issues/81147

<img width="322" alt="Screenshot 2021-10-29 at 09 55 06" src="https://user-images.githubusercontent.com/48132449/139405001-7e1d2b22-6d23-46a1-a6cc-a75ef1005ba7.png">

After talking to @sqren it turns out that we really didn't document that.

Can we please help customers to describe this feature a bit?

^^ @bmorelli25

**Comment by bmorelli25** [comment]
Hi @111andre111, this was doc'd in https://github.com/elastic/kibana/pull/98843. You can find the docs here: https://www.elastic.co/guide/en/kibana/current/service-overview.html#service-time-comparison. I'll close this issue, but let me know if you're expecting more on this topic and we can look into adding it.

**Comment by 111andre111** [comment]
Oh cool. Thank you, didn't find that one back then. Great.
