### ISSUE TITLE
Experimental -> technical preview

### ISSUE THREAD

**Issue by goodroot** [elastic/docs#2305]
Goal: move away from "experimental" language, replace with "technical preview"

We'll need to update the variable names and some text.

App logic: https://github.com/elastic/docs/blob/fa3ec61d6e1597a6d123106aca09c8e28ae034f1/resources/asciidoctor/lib/care_admonition/extension.rb#L17-L37

Specs: https://github.com/elastic/docs/blob/fa3ec61d6e1597a6d123106aca09c8e28ae034f1/resources/asciidoctor/spec/care_admonition_spec.rb

Owner: @goodroot

**Comment by jrodewig** [comment]
Talked about this offline with @goodroot:

We should consider maintaining the `experimental[]`, `experimental:[]`, and `experimental::[]` syntax for BWC. We can update the text for the rendered admonition without changing this syntax.

I’m fine with using a new syntax going forward, but if we remove the existing syntax, we’ll need to update _all_ versions of our docs that include it. This would be a pretty major chore with little benefit to end users.

**Comment by goodroot** [comment]
A most reasonable way forward, thanks James. :)
