### ISSUE TITLE
[Logstash] Hard to find the documentation about centralized configuration management

### ISSUE THREAD

**Issue by bahaaldine** [elastic/docs#234]
My goal as a user was to understand how to configuration logstash to use the configuration created in Kibana.

I started my journey [here](https://www.elastic.co/guide/en/logstash/6.0/logstash-centralized-pipeline-management.html) and saw the following quote:
> On the Logstash side, you simply need to register Logstash to use the centrally managed pipeline configurations.

But couldn't find the related documentation.

I randomly clicked on the Setting Up X-Pack link
https://www.elastic.co/guide/en/logstash/6.0/setup-xpack.html
then https://www.elastic.co/guide/en/logstash/6.0/installing-xpack-log.html
then https://www.elastic.co/guide/en/logstash/6.0/settings-xpack.html
and finally I found the doc: https://www.elastic.co/guide/en/logstash/6.0/settings-xpack.html#configuration-management-settings

I think the distance is too high and we should have a direct link in the quote above.

**Comment by dedemorton** [comment]
Thanks for submitting your feedback! I agree completely and fixed the issue a few days ago.

See https://www.elastic.co/guide/en/logstash/6.0/logstash-centralized-pipeline-management.html

Just an FYI for future comments: This repo is for issues related to the documentation infrastructure. For Logstash issues, go here: https://github.com/elastic/logstash/issues
