### ISSUE TITLE
The Spin up the Stack widget is out of date with the Cloud UI

### ISSUE THREAD

**Issue by DanRoscigno** [elastic/docs#2343]
Adding this issue here as the shared widget lives in this repo.  This is the widget:

<img width="811" alt="image" src="https://user-images.githubusercontent.com/25182304/148986688-b42b4104-2316-4ce4-bf48-ffcf921a1856.png">

It was fine originally, but there was a design change to the Cloud UI to remove the solution templates, and there is no longer a way to "select Elastic Observability."  Likewise, the Cloud ID is not made available to the viewer as they are popped into Kibana (to get the Cloud ID they can go back to the Cloud UI (leaving Kibana).  I will submit a PR to update the instructions and also open an issue to see if we can get the Cloud ID added to the screen displayed during the deployment creation process that provides the elastic password.  The screen I am referring to looks like so:

<img width="1182" alt="Screen Shot 2022-01-11 at 8 36 54 AM" src="https://user-images.githubusercontent.com/25182304/148987501-2e6c89cb-a785-4ecb-b864-1eb82c2e077d.png">

**Comment by gtback** [comment]
Thanks, @DanRoscigno

**Comment by DanRoscigno** [comment]
@kellyemurphy @florent-leborgne can you suggest how this should be raised with Design?  I would like to suggest in the "Save the  deployment credentials" step that the Cloud ID also be included in the display and download.  Probably also a note that endpoints and APM details are in the Deployments list.

**Comment by florent-leborgne** [comment]
@DanRoscigno, re: your question about suggesting change to the UI, the Design team has [a few items](https://github.com/elastic/global-cloud-design-team/issues?q=is%3Aissue+is%3Aopen+credentials) that mention this credentials screen, as well as the overall deployment creation flow. 
I am not sure about the timeline for these issues but maybe talking to Cristina would be a good starting point?
