### ISSUE TITLE
Add example of some painless exception handling

### ISSUE THREAD

**Issue by mimitsu** [elastic/docs#238]
The documentation only lists try and catch (for example) as reserved words. 

<img width="724" alt="screen shot 2017-09-20 at 10 53 28 am" src="https://user-images.githubusercontent.com/29132388/30650885-05bd9204-9df2-11e7-9cfe-dea6ae2a7c52.png">

Can we add some examples of exception handling somewhere??

**Comment by clintongormley** [comment]
@mimitsu This repo is only for the docs build infra, not the content.  Please open the issue in the elasticsearch repo instead.
