### ISSUE TITLE
Apply negative boost to old shield, watcher, graph, and marvel docs in search

### ISSUE THREAD

**Issue by colings86** [elastic/docs#242]
When you search for X-pack related features int eh documentation on the website often the old shield/watcher/graph/marvel results appear first (e.g. https://www.elastic.co/search?q=active+directory&section=Learn%2FDocs%2F) 

<img width="859" alt="screen shot 2017-10-04 at 10 54 11" src="https://user-images.githubusercontent.com/236731/31170009-746203ec-a8f2-11e7-8f29-d7ad0018003f.png">

It would be good if we could apply a negative boost to these books so they will appear lower in the list of results, below the X-Pack documentation

**Comment by dedemorton** [comment]
Closing because the search is changing completely with the move to Swiftype
