### ISSUE TITLE
Add Clarification To Meaning Of Logstash "pipeline.unsafe_shutdown" Configuration Parameter 

### ISSUE THREAD

**Issue by MorrieAtElastic** [elastic/docs#243]
The current discussion of the logstash "pipeline.unsafe_shutdown" parameter at https://www.elastic.co/guide/en/logstash/current/logstash-settings-file.html is as follows: 

__pipeline.unsafe_shutdown (default "false")__ 
_When set to true, forces Logstash to exit during shutdown even if there are still inflight events in memory. By default, Logstash will refuse to quit until all received events have been pushed to the outputs. Enabling this option can lead to data loss during shutdown._

See also the discussion about shutting down logstash at https://www.elastic.co/guide/en/logstash/current/shutdown.html

The description implies that while  setting pipeline.unsafe_shutdown to true can result in a loss of data when logstash is terminated, setting pipeline.unsafe_shutdown to false will not result in _any_ loss of data when logstash is terminated. This is not true: when pipeline.unsafe_shutdown is set to false, all events that have entered the logstash pipeline will be passed through to elasticsearch for indexing. However data which has been read from its source but has not yet entered the pipeline will  still be lost. 

This distinction  should be entered into the documentation at both of the locations given above. 

See https://github.com/elastic/support-dev-help/issues/2635 for more background on the reasons for this doc enhancement request.

**Comment by clintongormley** [comment]
@MorrieAtElastic This repo is only about the docs build infra, not the content.
