### ISSUE TITLE
X-Pack monitoring retention policy setting disappeared

### ISSUE THREAD

**Issue by bahaaldine** [elastic/docs#245]
If you on version 5.2 in this page: https://www.elastic.co/guide/en/x-pack/5.2/monitoring-settings.html
You will be able to find the `xpack.monitoring.history.duration` to configure the retention.

But the setting seems to have disappeared in version 5.6: 
https://www.elastic.co/guide/en/x-pack/5.6/monitoring-settings.html

**Comment by clintongormley** [comment]
@bahaaldine please open this issue on the appropriate repo.  The docs repo is only for the docs build process
