### ISSUE TITLE
Formatting issue on documentation menu for Microsoft Edge

### ISSUE THREAD

**Issue by a03nikki** [elastic/docs#2510]
- Page URL: https://www.elastic.co/guide/en/elasticsearch/reference/8.3/dissect-processor.html
- Device type: Laptop
- Specifics (e.g., OS, Hardware, Browser, etc.): Windows - Microsoft Edge 104.0.1239.47

List out steps on how to recreate the issue.
1. Open the webpage in Microsoft Edge
2. Try to scroll down to the end of the page to view the end of the menu

If you have a screenshot, add it below.
There were taken from a Zoom call with a user where he showed me the problem on 8/30 3:45pm US/Chicago (CT)
<img width="743" alt="2022-08-30 at 15 46 15_webpage" src="https://user-images.githubusercontent.com/2642763/187546790-e440d283-72d8-4b86-be24-9f942eb4fe27.png">
<img width="738" alt="2022-08-30 at 15 48 50_edge-settings" src="https://user-images.githubusercontent.com/2642763/187546795-7ce53334-9f8d-46db-b4c7-95289e4f64c6.png">

Which is different from how it renders in my Firefox browser on MacOS.  I have a scroll bar on the menu and it is on the left hand side.
![2022-08-30 at 16-46-42 Dissect processor Elasticsearch Guide 8 3 Elastic](https://user-images.githubusercontent.com/2642763/187549717-10cadae2-0bb0-4a4d-8d76-5584fdd26d8f.png)

User description of the problem:
> **Elastic Web Updates**
> Wed, Aug 24, 2022 at 2:33 PM CT
>
> Hi Nikki,
>
> If you want to pass along some feedback, whatever  happened to the Elastic website over the weekend is kind of a pain.  I  use Edge pretty exclusively and the menu on the side of the page does  not scroll all the way to the bottom of the page.  I would be happy to provide more info.  The page I am viewing is  [Dissect processor \| Elasticsearch Guide [8.3] \| Elastic](https://www.elastic.co/guide/en/elasticsearch/reference/8.3/dissect-processor.html)
>
> In Chrome, the menu shows up on the left of the  screen and works just fine.  In Edge, it shows up on the right of the  screen and will not scroll below the Lowercase processor reference on my  screen and I cannot scroll the menu separately.
>
> Thanks

**Comment by gtback** [comment]
Thanks, @a03nikki . I don't have a Windows machine to test on, but I used Edge on my Mac and I'm not seeing the problem. Based on the timing, I wonder if this is related to cached CSS from when we rolled out the new UI (#2478). If you happen to talk to the user again, can you check whether this is still a problem, or if a hard-refresh fixes it? Thanks!

cc: @bmorelli25 @colleenmcginnis

**Comment by bmorelli25** [comment]
Thanks, @a03nikki and @gtback!

I'm going to close this as it's more than likely a caching problem as explained above. @a03nikki please feel free to reopen if your user is still experience the problem after a hard refresh.

**Comment by a03nikki** [comment]
I got confirmation that it is display correctly as of 10/5/2022.
