### ISSUE TITLE
Beats Developer Guide points master

### ISSUE THREAD

**Issue by johtani** [elastic/docs#259]
https://www.elastic.co/guide/index.html

Should it point to 6.0 instead master?
Beats Platform Ref points 6.0.

And can we redirect old url to current url if we can?
e.g. : https://www.elastic.co/guide/en/beats/libbeat/current/new-beat.html
I think we changed Beats Developer Guide to top level from Platform Reference.

Now, we google "beat custom elastic", then [we got the list](https://www.google.co.jp/search?newwindow=1&source=hp&ei=yUsNWoz8Ncb78QXyib7oAQ&q=beat+custom+elastic&oq=beat+custom+elastic&gs_l=psy-ab.3..33i21k1.6710.10801.0.10916.21.17.0.0.0.0.301.2214.0j4j5j1.10.0....0...1.1.64.psy-ab..11.10.2214.0..0j46j0i46k1j0i203k1j0i10i203k1j0i10k1j0i13k1.0.H8gS4Ni3OVE) and the top is old URL.

**Comment by dedemorton** [comment]
The most current version of the Dev Guide content *is* in master, so the version of current in the docs is correct for the Dev Guide. 

You're right that a redirect is required for new-beat.html. We try to set up redirects when we move content, but it's a very manual process, and unfortunately this link was overlooked. I've opened an issue to get the redirect set up.

In the future, please go to the [beats](https://github.com/elastic/beats/issues) repo to identify Beats-related doc issues.

Thank you for helping us improve the documentation.
