### ISSUE TITLE
Improving the layout of multiple callouts

### ISSUE THREAD

**Issue by markwalkom** [elastic/docs#265]
Reported by @alanjames1987 [here](https://twitter.com/AlanJames1987/status/933548484300562432).

On [this page of the docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/analysis-custom-analyzer.html) we have a config;
<img width="581" alt="screen shot 2017-11-23 at 15 22 07" src="https://user-images.githubusercontent.com/3184718/33158929-39717c9e-d062-11e7-9b5b-1d9f93cf3215.png">

And the 6 blue dots are highlighted and explained below;
<img width="819" alt="screen shot 2017-11-23 at 15 21 52" src="https://user-images.githubusercontent.com/3184718/33158940-4d7d18ec-d062-11e7-8019-04dcd7f755ab.png">

What's not really clear to readers is that the 6 dots (known as `callouts`) are all related to that same text definition.

Is this an asciidoc implementation issue, or can we improve this layout?

**Comment by debadair** [comment]
Totally agree this is visually unappealing and confusing. The first time I saw it, I thought it was a bug & content was missing.

**Comment by kellyemurphy** [comment]
Another example noticed by a customer h
![dnyoeqwvsaa8l_6](https://user-images.githubusercontent.com/18013151/45713450-ba2da280-bb54-11e8-83bd-b3970e480f69.jpg)
ttps://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-source-field.html  
source file https://github.com/elastic/elasticsearch/edit/6.4/docs/reference/mapping/fields/source-field.asciidoc

**Comment by geekpete** [comment]
Another example is here:

![screen shot 2018-12-04 at 12 51 26 pm](https://user-images.githubusercontent.com/2070843/49416004-33d44480-f7c4-11e8-80a2-660a74806b18.png)



https://www.elastic.co/guide/en/elasticsearch/reference/master/removal-of-types.html

source file: https://github.com/elastic/elasticsearch/edit/master/docs/reference/mapping/removal_of_types.asciidoc

**Comment by gtback** [comment]
This appears to have been resolved the way I would have expected, by making multiple callouts with the same number.
