### ISSUE TITLE
ECE Installation note

### ISSUE THREAD

**Issue by damianpfister** [elastic/docs#272]
Recently a customer hit an issue installing the latest ECE 1.1.1 due to an incompatibility with having a previous version in his docker registry locally. This created a lot of challenges which were resolved by removing all previously used docker installations. This would be avoided if the documentation clearly stated that ECE be installed in a clean environment, with the following precursor applied:

1. docker rm -f $(docker ps -a -q)
2. docker volume rm $(docker volume ls -q)
3. reboot

references:
https://github.com/elastic/support-dev-help/issues/2962
https://discuss.elastic.co/t/ece-failed-to-install/110359/4

**Comment by dedemorton** [comment]
Closing because this issue needs to be opened in the cloud repo. cc @nrichers
