### ISSUE TITLE
Set up X-pack and its child pages are missing the Edit Me button

### ISSUE THREAD

**Issue by sandeepkanabar** [elastic/docs#286]
The Set up X-Pack page at https://www.elastic.co/guide/en/elasticsearch/reference/5.5/setup-xpack.html and all its child pages are missing the `Edit Me` button. The net result is that we cannot correct / submit documentation error bugs. 

The monitoring collection settings at https://www.elastic.co/guide/en/elasticsearch/reference/5.5/monitoring-settings.html#monitoring-collection-settings wrongly mentions the default interval to be 10m i.e 10 minutes. It should be 10s i.e 10 seconds.

The same issue is present for Elasticsearch docs corresponding to version 5.6 also.

**Comment by lcawl** [comment]
Thanks @sandeepkanabar, I can follow up on the monitoring setting details. 

You cannot edit the X-Pack-related pages yet, since they're maintained in private repositories.  That will change in the near future though, per https://www.elastic.co/blog/doubling-down-on-open

**Comment by lcawl** [comment]
The default value for xpack.monitoring.collection.interval is documented as "10s" all the way back to 5.4 (https://www.elastic.co/guide/en/x-pack/5.4/monitoring-settings.html), so no changes seem to be required.

**Comment by sandeepkanabar** [comment]
@lcawl - I am talking about ES `5.5`. version. Please see the link https://www.elastic.co/guide/en/elasticsearch/reference/5.5/monitoring-settings.html#monitoring-collection-settings wherein it's written `10m` instead of `10s`.

The same issue is present for Elasticsearch docs corresponding to version `5.6` also. For `5.4`, this page doesn't exist and for `6.0`, it has been corrected to `10s`.
