### ISSUE TITLE
The `Copy as curl` function doesn’t work for PATCH requests

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/docs#2966]
The `Copy as curl` function doesn’t work for PATCH requests across multiple docsets (confirmed in Security and Kibna docs). Examples:
- https://www.elastic.co/guide/en/security/current/rules-api-update.html#_example_request_3
- https://www.elastic.co/guide/en/kibana/8.12/cases-api-update-comment.html#_examples_33

To fix this, will need to:

- [x] Add `PATCH` to [this](https://github.com/elastic/docs/blob/master/resources/web/docs_js/utils.js#L28) docs build component
- ~Add `PATCH` to [this code](https://github.com/elastic/elasticsearch/blob/main/build-tools-internal/src/main/groovy/org/elasticsearch/gradle/internal/doc/RestTestsFromSnippetsTask.groovy), which is where the above file was copied from.~ Holding off on fixing the ES file since there are no `PATCH` operations in the ES docs at the moment.

**Comment by 111andre111** [comment]
Perfect. Example preview page seems to work:
https://docs_bk_2967.docs-preview.app.elstc.co/guide/en/security/current/rules-api-update.html#_example_request_3

**Comment by nastasha-solomon** [comment]
Merged https://github.com/elastic/docs/pull/2967.
