### ISSUE TITLE
mongodb-start out of date, Mongodb Atlas now forces TLS/SSL

### ISSUE THREAD

**Issue by dlin2028** [elastic/docs#3058]
In [mongodb-start](https://www.elastic.co/guide/en/enterprise-search/current/mongodb-start.html), the tutorial failes to mention TLS/SSL. Without enabling TLS/SSL the connector will fail to connect to Mongodb Atlas, which now forces the use of TLS/SSL.

I would like to update mongodb-start, however I can't find where to do that. I checked conf.yaml but I don't seem to have access to any of the links, and I can't find the correct link. Can someone point me in the right direction?

**Comment by leemthompo** [comment]
Hey @dlin2028, thanks so much for flagging and opening a ticket. Those docs live in a private repo for the moment. I'll investigate this one and report back :)

For future reference, you can open issues in https://github.com/elastic/connectors and we'll reroute from there.
