### ISSUE TITLE
support matrix compatibility clarity around x-pack

### ISSUE THREAD

**Issue by robin13** [elastic/docs#313]
A customer today asked why she couldn't install x-pack 6.1.1 on elasticsearch 6.1.3 because the compatibility matrix says you can:
https://www.elastic.co/support/matrix#matrix_compatibility

The intention here is that the x-pack **features** of 6.1.1 are compatible with 6.1.3 (i.e. a 6.1.3 elasticsearch node can send x-pack::monitoring data to an elasticsearch 6.1.3 cluster (both with x-pack installed).  If you are installing x-pack on elasticsearch, they must be _exactly_ identical versions, but this nuance is not really clear from the table.
Would it be possible to clarify that detail?

**Comment by clintongormley** [comment]
This issue was moved to elastic/website-www.elastic.co#2295
