### ISSUE TITLE
Missing - Cluster Alerts for Elasticsearch Nodes

### ISSUE THREAD

**Issue by eddieturizo** [elastic/docs#318]
```
/x-pack-elasticsearch-6.2.2/plugin/monitoring/src/main/java/org/elasticsearch/xpack/monitoring/exporter/ClusterAlertsUtil.java```

```
    public static final String[] WATCH_IDS = {
        "elasticsearch_cluster_status",
        "elasticsearch_version_mismatch",
        "kibana_version_mismatch",
        "logstash_version_mismatch",
        "xpack_license_expiration",
        "elasticsearch_nodes",
    };

[https://www.elastic.co/guide/en/kibana/6.2/cluster-alerts.html](https://www.elastic.co/guide/en/kibana/6.2/cluster-alerts.html)

The Cluster Alerts documentation includes

- Elasticsearch Cluster Health Status
- Elasticsearch Version Mismatch
- Kibana Version Mismatch
- Logstash Version Mismatch 
- X-Pack License Notification 

but does not include 

- Elasticsearch Nodes

<img width="1951" alt="screen shot 2018-03-12 at 3 30 45 pm" src="https://user-images.githubusercontent.com/20506300/37307694-201d0b9a-2612-11e8-9178-dd5a70792297.png">

My thinking is that we forgot to add Elasticsearch Nodes as an alert in the documentation. Is that the case?

**Comment by dedemorton** [comment]
@eddieturizo Can you please open this issue in the https://github.com/elastic/x-pack-kibana/ repo? This repo is for doc infrastructure related issues.
