### ISSUE TITLE
Add "copy code" functionality for command examples

### ISSUE THREAD

**Issue by dedemorton** [elastic/docs#319]
When users try to copy/paste a command example that spans multiple lines and has callouts, the callouts are replaced with empty spaces, which breaks the command.

For example:

![image](https://user-images.githubusercontent.com/14206422/37441079-cc21894c-27bc-11e8-90f0-5a96de3bfce7.png)

It would be nice to provide users with a link or icon (similar to the "copy as curl" link for CURL examples) that copies the code with continuation characters, but without the extra spaces added by callouts.

Edited: Note that this example comes from https://www.elastic.co/guide/en/beats/metricbeat/current/running-on-docker.html

**Comment by nik9000** [comment]
I wonder if we'd be better off making highlighting and copying actually skip the callouts somehow....

**Comment by dedemorton** [comment]
@tylersmalley This was the code copying issue I mentioned to you recently. Nik makes an excellent point. Do you know if this is possible/feasible?

**Comment by dedemorton** [comment]
Also see https://github.com/elastic/docs/issues/166

**Comment by dedemorton** [comment]
Also see https://github.com/elastic/docs/issues/210

**Comment by dedemorton** [comment]
Closing because this is quite old and will not be implemented in asciidoc.
