### ISSUE TITLE
yellow box link at the top of a page brings to the index

### ISSUE THREAD

**Issue by immon** [elastic/docs#327]
Many times I read the docs of version 5.x but want to check version 6.x. I have 5.x doc links in web-browser history or google gives me those results at the top.

Then when reading 5.x doc I click in the yellow box in the top `You are looking at documentation for an older release. Not what you want? See the current release documentation.` This however brings me to the index of not to the API doc I'm reading about. It is very frustrating and I expect to see the same API doc but for a current version. Not a chapters index .

If I select a version on the right hand side from the select box it works correctly.

An example, but there are many more: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docs-reindex.html

I understand that if a file path for the same API has changed in 6.x branch there is a little we can do, but for Reindex API I'm giving an example to the file path is the same
https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docs-reindex.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html

**Comment by debadair** [comment]
Superseded by: https://github.com/elastic/docs/issues/1743
