### ISSUE TITLE
I can't found index.asciidoc in docs repo

### ISSUE THREAD

**Issue by fapwlh** [elastic/docs#331]
I'm sorry that ,I can't found index.asciidoc in the whole repo, can tell me where found it....thanks🙏

**Comment by lcawl** [comment]
If you tell me which book you are trying to build, I'm happy to help.  
In general, you can find the recommended commands for building all the books (including the main asciidoc file that is used to build them) here: https://github.com/elastic/docs/blob/master/doc_build_aliases.sh

**Comment by fapwlh** [comment]
thank you very much 😊
