### ISSUE TITLE
Code snippet is too big causing text to be displayed as code

### ISSUE THREAD

**Issue by melvynator** [elastic/docs#333]
The code snippet is not properly close on this page: [https://www.elastic.co/guide/en/elasticsearch/reference/6.2/index-modules.html](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/index-modules.html)

This cause some text to be displayed as code instead of text:

<img width="865" alt="screen shot 2018-04-17 at 09 25 46" src="https://user-images.githubusercontent.com/5473562/38840346-76ddcb82-4222-11e8-9c27-86898dfdc40f.png">

**Comment by lcawl** [comment]
Thanks for noticing this error. I fixed it with https://github.com/elastic/elasticsearch/commit/944868908cf326a31043e86c7f4a222fbd221dab in 6.0 -> master branches.
