### ISSUE TITLE
Some documentation pages don't show hierarchy in search results

### ISSUE THREAD

**Issue by colings86** [elastic/docs#34]
If you search for 'metric aggregation' (https://www.elastic.co/search?q=metric+aggregation) in the Elasticsearch documentation the links appear with the hierarchy in the title (e.g. Scope of scripts » Scripted Metric Aggregation | Reference | Elasticsearch).

However if I search for 'percolator' (https://www.elastic.co/search?q=percolator) the first two results have the same title (Percolator | Reference | Elasticsearch) but the first result is actually a reference to the breaking changes document. This first link should have the hierarchy in the title so you can easily see it is a breaking changes doc and not the actual documentation for the Percolator.

**Comment by dedemorton** [comment]
Search is changing significantly soon, so I'm closing this issue as it will no longer be relevant.
