### ISSUE TITLE
Rolling upgrade, use transient settings to disable shard allocation

### ISSUE THREAD

**Issue by bharath-elastic** [elastic/docs#343]
Here [https://www.elastic.co/guide/en/elasticsearch/reference/current/rolling-upgrades.html](url)
Step 1: Disable shard allocation using persistent settings
.
.
Step 7: Enable shard allocation using transient settings (overrides persistent)
.
.
Step 9: Repeat steps for every node 
If I repeat step 1 for the next node and disable shard allocation using **"persistent settings"**, that wouldn't override the enabled shard allocation (which was set using transient settings in Step 7 of previous iteration) and won't get disabled correct? Unless I am missing something this is a bug? Please confirm.

**Comment by debadair** [comment]
The docs need further changes. There's an issue for this in the ES repo: https://github.com/elastic/elasticsearch/issues/27677

FYI, content issues should be opened in the appropriate product repo. We use this repo to track doc infra issues.
