### ISSUE TITLE
Main example in the top-level mappings documentation doesn't render correctly. 

### ISSUE THREAD

**Issue by jtibshirani** [elastic/docs#347]
See the 'Example mapping' section in https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html:

<img width="1606" alt="screen shot 2018-04-30 at 1 57 20 pm" src="https://user-images.githubusercontent.com/7461306/39449973-83d12260-4c7e-11e8-86e3-9d9267eef31d.png">

It looks like this issue is caused by using duplicate callouts (in this case, multiple instances of `<4>` in the same block).

**Comment by debadair** [comment]
Thanks @jtibshirani. This is "working as designed" but is less than ideal. There's an outstanding issue for it (#265) and we're tracking it as part of our Doc Enhancements Wishlist (#336).
