### ISSUE TITLE
Clarification on Conditions of Use

### ISSUE THREAD

**Issue by gsaslis** [elastic/docs#350]
The first section in your `README` lays out the conditions of use for this repository. 

I am wondering if it would be fair game to fork the process and basically reuse your docs building process for building docs of some external 3rd party project ... ?

Clearly, this would in no way involve Elastic's content, we would just copy your approach, to create our own docs. 

Is this against the conditions of use (as it's not included in them)?
Does that sound like an appropriate use of this repo? Or is the process too tightly coupled to the actual Elastic content, website, hosting, etc. so there would be a lot of wasted time trying to extract that out?

**Comment by debadair** [comment]
The build infra in this repo is tightly coupled with the Elastic content and website. I would recommend checking out https://gitlab.com/antora/antora for an open source solution for building content sites from asciidoc source files.

**Comment by dedemorton** [comment]
Closing this because the conditions of use seem clear and the response given is accurate.
