### ISSUE TITLE
Kibana 6.0 reference CN

### ISSUE THREAD

**Issue by medcl** [elastic/docs#351]
Hi, Deb
Our awesome community members are going to finish the translation of Kibana reference soon（v6.0 ），I'd like to start the launch process of this docs now,
The repo is here: https://github.com/elasticsearch-cn/kibana

Currently, they are busy at doing the final review of the reference, the preview can be found below:
http://167.160.183.150:8080/cn/index.html

Can you help to process it?
Thanks!

**Comment by debadair** [comment]
Cool. Is there any reason not to add it now, along with the PHP translation?

**Comment by debadair** [comment]
It's now live at https://www.elastic.co/guide/cn/kibana/current/index.html

**Comment by medcl** [comment]
Thank you @debadair
