### ISSUE TITLE
Blank Topic on Marvel Documentation

### ISSUE THREAD

**Issue by alefeans** [elastic/docs#360]
Hi !

There is a blank topic on the Marvel Documentation:

https://www.elastic.co/guide/en/marvel/current/installing-marvel.html#marvel-prequisites

Regards !

**Comment by lcawl** [comment]
I do see an empty item in the bulleted list on that page. However, that content is no longer actively updated.  For the latest monitoring pages, please see the links in https://www.elastic.co/guide/en/elastic-stack-overview/6.5/xpack-monitoring.html
