### ISSUE TITLE
Docs navbar covers title when a link to a header is selected

### ISSUE THREAD

**Issue by malake** [elastic/docs#368]
I've noticed when searching through the docs pages if I click a link that is a header further down in a page the navbar that scrolls with the page covers the header. This is probably pretty low on the list of things because you can scroll up one click, but I'm new to ES and my initial response was confusion. The page/header is linked properly, but the `<div class="tertiary-nav bdr-btm-e0e0e0 navbar-fixed-top">` is just covering the section title I expected to see. 

[Example](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/_basic_concepts.html#getting-started-shards-and-replicas)

**Comment by nik9000** [comment]
We have removed this nav bar! Sorry for no response in a whole year. All better now though.
