### ISSUE TITLE
has_child nonsupport must_not?

### ISSUE THREAD

**Issue by aa0604** [elastic/docs#379]
{
    "query": {
        "bool": {
            "must": [
                {
                    "term": {
                        "sex": 1
                    }
                },

                {
                    "has_child": {
                        "type": "like",
                        "query": {
                            "bool": {
                                "must_not": [
                                    {
                                        "term": {
                                            "actionUserId": 2
                                        }
                                    }
                                ]
                            }
                        }
                    }
                }
            ]
        }
    }
}

**Comment by gtback** [comment]
Hi! This seems to be a question about Elasticsearch itself, so if the documentation isn't clear, I'd recommend asking on [the discussion forums](https://discuss.elastic.co/) or in the Elasticsearch repo itself.
