### ISSUE TITLE
Clarify new X-Pack documentation location (6.3+)

### ISSUE THREAD

**Issue by ppf2** [elastic/docs#381]
A lot of users/customers may not be up to date on the opening of X-pack and what it means when it comes to moving x-pack artifacts into Elasticsearch.  

It will be nice to have some static text telling the end user where to go for X-Pack 6.3 documentation now (i.e. they have been moved within the Elasticsearch main reference and Elastic stack overview guides) given that all the sections show 6.3 guides when X-Pack remains on 6.2.

![image](https://user-images.githubusercontent.com/7216393/41443818-fd9e7186-6ff3-11e8-89b4-a8c2be179964.png)

**Comment by lcawl** [comment]
The X-Pack Reference has been moved to the "Legacy" section of the landing page. It is no longer indexed (i.e. the pages have `<meta name="robots" content="noindex,nofollow" />`) and each page has a link to the Stack Overview:

![image](https://user-images.githubusercontent.com/26471269/58502730-fb427180-813b-11e9-81eb-0fe956c96308.png)
