### ISSUE TITLE
Install X-Pack into Logstash step in 6.3 Upgrade Guide 

### ISSUE THREAD

**Issue by inqueue** [elastic/docs#387]
The Elastic Stack 6.3 Upgrade Guide has a step for installing X-Pack into Logstash. 

![screen shot 2018-06-26 at 6 22 23 pm](https://user-images.githubusercontent.com/6099128/41942903-69fa13ba-796f-11e8-81a3-8fcd4d41d26e.png)

***

This could cause confusion since X-Pack ships with Logstash; there is nothing to install. Steps to get there:

What version of Elasticsearch are you currently running? **5.6**
Are you running in Elastic Cloud? **No**
Which products are you using with Elasticsearch? **Kibana, Logstash, Beats**
_Next_
Do you use X-Pack? **Yes**
Which X-Pack features do you use? **Security, Watcher/Alerting, Monitoring**
_Next_
Do you have TLS enabled? **Yes**
Do you have any indices that were created in 2.x? **No**

**Comment by inqueue** [comment]
Sorry @lcawl, I didn't mean to leave you guessing! Yes, this is in the interactive upgrade guide. I followed the [Interactive Upgrade Guide](https://www.elastic.co/products/upgrade_guide) link at https://www.elastic.co/guide/en/logstash/current/upgrading-logstash.html. The error is in the interactive guide itself.

**Comment by damianpfister** [comment]
Seen at least two cases where the customer upgraded Logstash from 6.2 to 6.3 without first removing x-pack which then shows it as being the older x-pack installed in the newer Logstash. The solution is to first remove x-pack in 6.2 (like we say in Elasticsearch) before installing Logstash 6.3 which has x-pack bundled.
