### ISSUE TITLE
Add warning link to HTTP auth to Watcher tutorial as it breaks for people with shield

### ISSUE THREAD

**Issue by derickson** [elastic/docs#40]
Users following this instruction set for the first time may not realize that they need to authenticate in their HTTP input when calling against a Shield secured ES.   I think it would be useful to add a note and link to those instructions.

Tutorial:
https://www.elastic.co/guide/en/watcher/current/watch-cluster-status.html

Instruction to link to:
https://www.elastic.co/guide/en/watcher/current/input.html#_calling_external_webservices

**Comment by dedemorton** [comment]
Closing because this is quite old and opened in the wrong repository. The docs repo is for doc tools-related issues only.
