### ISSUE TITLE
Problem with docs branch selection

### ISSUE THREAD

**Issue by jahtalab** [elastic/docs#414]
I see an issue on this page of the docs: https://www.elastic.co/guide/en/apm/agent/js-base/0.x/index.html,
When I select the 1.x (current) branch it works as expected but when I change that to 0.x, the 1.x branch disappears from the dropdown selection and 0.x becomes the current.
Note: the 1.x branch was recently added via https://github.com/elastic/docs/pull/413

![image](https://user-images.githubusercontent.com/6134122/44571333-c9514880-a780-11e8-8a44-a00839a6d768.png)

![image](https://user-images.githubusercontent.com/6134122/44571343-d3734700-a780-11e8-8934-02d66eac9c4e.png)

**Comment by lcawl** [comment]
I've rebuilt the full set and pushed the changes to the docs repo. Looks good to me now.

**Comment by jahtalab** [comment]
Thanks! It now works as expected!
