### ISSUE TITLE
Date Histogram Aggregation and empty Buckets

### ISSUE THREAD

**Issue by pasfreelance** [elastic/docs#42]
Hi,

i am new to Elastic and work a lot with the Docs. I've mapped my "date" fields with the format "DateTimeOptional".

This is not working with the Date Histogram Aggregation. With "DateTimeOptional" i receive empty Buckets every time. You have to define a Format for your Date field in the Mapping as like "yyyy-MM-dd" to get it work.

Maybe there should be a notice in the Date Histogram Aggregation Documentation?

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html

I hope i choosed the right repository for creating the Issue?

Thanks in Advance

**Comment by clintongormley** [comment]
Hi @pasfreelance 

I think you're doing something incorrect.  The best place to ask is in the forum: http://discuss.elastic.co/

This repo is for bug/features in the docs build process.
