### ISSUE TITLE
Refer to doc_build_aliases.sh in README

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/docs#421]
I was unaware that there are [useful aliases for building the documentation](https://github.com/elastic/docs/blob/586255f82caa418fe5668d30af0b17e3b9155781/doc_build_aliases.sh) maintained within this repository, until I read this comment: https://github.com/elastic/elasticsearch/issues/33101#issuecomment-416278393 (see also https://github.com/elastic/docs/issues/415#issuecomment-415840406). I think it'd be useful for this information to be included in the README of this repository, since that is one of the places I looked when trying to find these instructions.

**Comment by debadair** [comment]
Done: https://github.com/elastic/docs/blob/master/README.asciidoc#building-documentation
