### ISSUE TITLE
[DOCS] Create "getting started with Elastic Stack"

### ISSUE THREAD

**Issue by lcawl** [elastic/docs#423]
We would like to create a "Getting started" section directly under the "Elastic Stack" section of the documentation home page (https://www.elastic.co/guide/index.html).

This will initially contain the following content: https://www.elastic.co/guide/en/elastic-stack-overview/master/get-started-elastic-stack.html

- [x] Create high level container for this information. See https://github.com/elastic/docs/pull/424

- [x] Move the existing content from the Stack Overview. See https://github.com/elastic/stack-docs/pull/110

- [x] Update links to the existing content in the new location.

- [x] Create redirects from the old location. 

- [ ] Determine whether other product-level pages also need to be updated to link to this new site.

**Comment by dedemorton** [comment]
For the high level container, I'd propose adding the following structure under Elastic Stack on the landing page:

Getting Started
  Getting Started with the Elastic Stack
  Running the Elastic Stack on Docker
  Running the Elastic Stack on Kubernetes
