### ISSUE TITLE
max_expansions cannot be set to 0 in fuzzy queries

### ISSUE THREAD

**Issue by cwurm** [elastic/docs#43]
query-dsl-fuzzy-query.html states that `this query can be very heavy if prefix_length and max_expansions are both set to 0. This could cause every term in the index to be examined!`

Yet actually, `max_expansions` cannot be set to 0 as this results in a `SearchParseException`. See [#5017 in elasticsearch](https://github.com/elastic/elasticsearch/issues/5017) on this.

**Comment by clintongormley** [comment]
Hi @cwurm 

The docs repo is for the build process only.  Issues like this should be opened on the repo holding the docs source (https://github.com/elastic/elasticsearch/issues in this case)

thanks

**Comment by cwurm** [comment]
Thanks @clintongormley, I opened https://github.com/elastic/elasticsearch/issues/14092.
