### ISSUE TITLE
[DOCS] Create Stack Documentation for Multi-Cluster Architectures

### ISSUE THREAD

**Issue by zuketo** [elastic/docs#437]
Adding this issue as a placeholder, and to start discussion, for Stack documentation on multi-cluster architectures, use cases may include:
- DR/HA
- Multi-tenant applications
- One cluster per geography
- One cluster per application
- A read only cluster (for reporting purposes)
- Upgrades (using multiple clusters, and CCS)
- Combination of items above (e.g. one cluster per application per region)

This documentation will be especially important as Cross Cluster Replication (CCR) gains popularity.

In terms of specific products: 
- Using Cross Cluster Search (CCS) with Kibana, Elasticsearch, and Beats across multiple clusters/DCs
  - For instance, querying across multiple-tenants, geographies, etc.
- Using Cross Cluster Replication (CCR) with Kibana for logging/metrics use cases
  - DR/HA

CC @robin13

**Comment by lcawl** [comment]
It seems to me that this type of content can likely be added to an existing book (e.g. https://www.elastic.co/guide/en/elastic-stack-overview/current/index.html)

**Comment by zuketo** [comment]
Closing, I think a few other projects / issues will help here.
