### ISSUE TITLE
Add note about mutate filter plugin configuration option execution order

### ISSUE THREAD

**Issue by eddieturizo** [elastic/docs#442]
Our documentation does not mention the execution order for the configuration options available in the mutate filter plugin when implemented in a Logstash pipeline configuration file. Based on [logstash-plugins/logstash-filter-mutate#28](https://github.com/logstash-plugins/logstash-filter-mutate/issues/28) order is ignored and instead performs execution as defined in `mutate.rb`. 

It would be helpful it our documentation made note of this so user's are made aware prior to implementation.

**Comment by karenzone** [comment]
Fixed in https://github.com/logstash-plugins/logstash-filter-mutate/pull/128
