### ISSUE TITLE
Clarify Precision function in Timelion Kibana

### ISSUE THREAD

**Issue by jaijhala** [elastic/docs#444]
There seems to be a confusion with how Precision function really works. 

The description of .precision only says the data is rounded, but doesn't specify a direction, like rounded down (it does imply one by using the name "precision"). If we follow normal rounding rules, 0.99 would be rounded to 1 where 0.99 with a precision of 0 would be 0 as in 0.99 with no decimal places.

I think it would be good to clarify this maybe with an example as well or a note that the excess decimals are dropped or the number is "rounded down" to precision instead of just "rounded".

**Comment by lcawl** [comment]
I've created https://github.com/elastic/kibana/issues/26100.  If you have additional info or documentation links to contribute, please add them there!
