### ISSUE TITLE
Docs HTML / elastic.co search

### ISSUE THREAD

**Issue by brianjolly** [elastic/docs#449]
Hi Everyone,
Question about https://github.com/elastic/docs/blob/master/html/index.html. Can someone let me know how the `DC.identifier` and `DC.subject` meta tags are set for that file?

The current values of those tags are causing an issue with the new Swiftype implementation on elastic.co

https://github.com/elastic/elastic-co-search/issues/34

Thanks!

**Comment by debadair** [comment]
@brianjolly These were added by https://github.com/elastic/docs/pull/312. They really shouldn't be injected at all into the top-level index page. However, if you can squelch the empty tags, I think simply setting version to an empty string in docs/Util.pm will do the trick. I'll make the change locally and run a build.

**Comment by brianjolly** [comment]
Hi @debadair!

So would the meta tag on the index page look like this?
`<meta name="DC.identifier" content="" />`

If that is possible, it should fix the problem. Thank You!

**Comment by brianjolly** [comment]
Thanks @debadair!
