### ISSUE TITLE
Add legend for icons in Kibana Discover

### ISSUE THREAD

**Issue by larry-hernandez** [elastic/docs#454]
It would be nice to include an icon legend in our [Discover](https://www.elastic.co/guide/en/kibana/current/discover.html) doc. 

![2018-10-31_16-47-24](https://user-images.githubusercontent.com/36249578/48080941-89f99c00-e1b4-11e8-891b-c6123811f122.png)

**Comment by gtback** [comment]
Hi @larry-hernandez. I believe hovering over the icon shows a tooltip explaining the field type. If that's not sufficient, I'd open an issue in the kibana repo, which is where this would actually get fixed.
