### ISSUE TITLE
Add Elasticsearch DSL Python client to Elasticsearch Clients

### ISSUE THREAD

**Issue by inqueue** [elastic/docs#47]
The [Elasticsearch DSL Python](https://github.com/elastic/elasticsearch-dsl-py) [1] client is missing from [Elasticsearch Clients](https://www.elastic.co/guide/en/elasticsearch/client/index.html) [2] page which is confusing customers. Can we add a reference to this client to either the main clients page or the one specific to [Python API](https://www.elastic.co/guide/en/elasticsearch/client/python-api/current/index.html) [3]?

@HonzaKral 

[1] https://github.com/elastic/elasticsearch-dsl-py
[2] https://www.elastic.co/guide/en/elasticsearch/client/index.html
[3] https://www.elastic.co/guide/en/elasticsearch/client/python-api/current/index.html

**Comment by HonzaKral** [comment]
Absolutely, this makes sense.

I already refer to the DSL from the README (0), but should probably make it more prominent. Will then send a PR to update the python API page in official docs.

0 - https://github.com/elastic/elasticsearch-py

**Comment by HonzaKral** [comment]
PR sent as https://github.com/elastic/elasticsearch/pull/14437

**Comment by dedemorton** [comment]
Closing - looks like this was fixed in https://github.com/elastic/elasticsearch/pull/14437
