### ISSUE TITLE
Proposal for adding conditional roles to the docs

### ISSUE THREAD

**Issue by dedemorton** [elastic/docs#476]
We don't want to hard code license information into individual doc source files because it would be a maintenance nightmare. But at the same time, it's hard for users to know which licenses they need to use specific feature. 

I propose that we store license information in a single, separate file so that the information can be changed easily.

We could accomplish this with our existing infrastructure. Here's one possible solution:

1 - Add a shared file that uses aciidoc attributes to map every commercial feature to a license. For example, you might have a file called `license-states.asciidoc` to contains a list of attributes:

````
:beats_config_mgt: gold
:beats_monitoring: basic
:HA_alerting: gold
````

2 - Add support to the doc build for all license states. For example, the build would support roles like:

[role="gold"] and [role="basic"]

When rendered, the topics would have a badge that says "Gold" or "Basic".

3 - add conditional statements to `license-states.asciidoc` to set the role based on the value of an attribute called `feature`:

````
ifeval::["{feature}"=="beats_config_mgt"]

[role="{beats_config_mgt}"]

endif::[]

ifeval::["{feature}"=="beats_monitoring"]

[role="{beats_monitoring}"]

endif::[]

ifeval::["{feature}"=="HA_alerting"]

[role="{HA_alerting}"]

endif::[]

````

4 - Instead of hard coding the role in our source files, use an asciidoc include to pull `license-state.docs` into the source files, setting the feature attribute to indicate the feature you are documenting.  For example:

````
:feature: beats_config_mgt
include::license-states.asciidoc[]
:feature!:
````

Not sure where the shared file would live, but we'd need to be able to version the file.

**Comment by dedemorton** [comment]
@elastic/docs This is the idea that I was trying to describe at our meeting today. With all the licenses defined in a single file, it would be easy to get someone from sales/marketing to review.

**Comment by kellyemurphy** [comment]
I like this idea, but wouldn't there still be maintenance of labelling everything as a feature?

Side note, there are two subscription pages - the [main subscription page](https://www.elastic.co/subscriptions) and [Cloud](https://www.elastic.co/cloud/elasticsearch-service/subscriptions). They use the same terms to describe slightly different things.

**Comment by dedemorton** [comment]
Right now, we need to add the role tag manually anyhow. Setting the feature isn't that much work for new stuff...it would require us to clean up the existing content, but it would be a one-time step.

**Comment by dedemorton** [comment]
So...instead of typing:

```
[role="xpack"]
```

You would type:

```
:feature: beats_config_mgt
include::license-states.asciidoc[]
:feature!:
```

**Comment by dedemorton** [comment]
@kellyemurphy We would probably need additional attributes for cloud, but are you saying that features marked as Gold in a product like Elasticsearch might not be Gold in the Hosted ES? If so, that would def cause confusion, and maybe differentiating by using different badges is not the way to go.

**Comment by dedemorton** [comment]
Closing because we've been told explicitly that we do not want to do this.
