### ISSUE TITLE
Add ability to have different tags on different versions of books

### ISSUE THREAD

**Issue by lcawl** [elastic/docs#482]
I believe that the "tags" field in the https://github.com/elastic/docs/blob/master/conf.yaml is applied to all versions of the book identically.  It would be helpful to be able to tag different versions differently (e.g. to add an indication that older releases are "legacy" content when they're beyond their end of life date https://www.elastic.co/support/eol)

Related to https://github.com/elastic/docs/pull/489

**Comment by lcawl** [comment]
Perhaps instead of making the tags field version-aware, an alternative solution could be to add a new "legacy" field that lists the out-dated versions for each book. Though if we wanted to be able to customize other tags by version, that solution wouldn't be as flexible.

**Comment by jonasll** [comment]
The latter will be difficult for us to consume from a crawler extraction perspective.

**Comment by lcawl** [comment]
Sorry for any confusion.  I meant adding something like this in the conf.yaml:
legacy: [2.1, 2.0, 1.7, 1.6, 1.5, 1.4, 1.3, 0.90 ]
And then maybe handling those cases in the build_search_index.pl (sub _index_book section) such that they tack on another "legacy" tag (or whatever that label needs to be). 
Someone closer to this code likely has a better idea, especially if we're considering other significant changes to our build system.

**Comment by lcawl** [comment]
I think this enhancement might no longer be required after we migrate to asciidoctor since it seems to support the addition of "keywords" on a book by book (version by version) basis: https://asciidoctor.org/docs/user-manual/#keywords

i.e. After we migrate some books with old versions, I'll try adding `:keywords: legacy` to see if that's respected by our search.

**Comment by debadair** [comment]
We can now inject metadata with the `keywords` and `description` attributes, and custom metadata via a docinfo.html file. Between that and our "live" version changes, I think we have the mechanism in place. (Tuning/rearchitecting search is a separate issue.)
