### ISSUE TITLE
Generate previews for books affected by documentation changes

### ISSUE THREAD

**Issue by lcawl** [elastic/docs#483]
Currently to preview their documentation changes, PR owners must build the appropriate book(s) locally.  If there are multiple pages (or the layout of the book) affected, sometimes we build the books locally then host them on a website for easier review. 

Rather than requiring PR owners to take these manual steps, we should integrate them in the PR process.

There are tools that facilitate generating and hosting previews automatically for PRs that contain doc changes. This would help authors quickly see if there are formatting errors and make a better overall review experience.

**Comment by nik9000** [comment]
@kellyemurphy pointed out that it'd be nice to be able to [annotate](http://annotatorjs.org/) the previews too!

**Comment by nik9000** [comment]
The previews are now live for any repos that have the universal docs build PRs. Annotation sounds fun though!
