### ISSUE TITLE
ODBC: SQL Access to contain ODBC link

### ISSUE THREAD

**Issue by bpintea** [elastic/docs#488]
The `SQL Access` menu/ToC at https://www.elastic.co/guide/en/elasticsearch/reference/6.5/xpack-sql.html should contain an ODBC link as well:
<img width="1189" alt="screen shot 2018-11-26 at 22 43 19" src="https://user-images.githubusercontent.com/1562801/49044124-2ff56080-f1cd-11e8-90fc-f32f767f4811.png">

**Comment by debadair** [comment]
Because the ODBC doc is currently separate, it's not possible to add it to the TOC links. Once we integrate it, it will show up in the TOC.
