### ISSUE TITLE
auditbeat Common fields clarification

### ISSUE THREAD

**Issue by TomonoriSoejima** [elastic/docs#501]
https://www.elastic.co/guide/en/beats/auditbeat/current/exported-fields-common.html

data in `event.action` actually show up as a list and wonder if we can add some comment in the description about it.

**Comment by webmat** [comment]
Strange, it's actually meant to be a single value. I'm seeing this on 6.5.1 as well.

I think you should instead create a GitHub issue on Beats, for Auditbeat. This looks like a small bug.

**Comment by gtback** [comment]
Hi @TomonoriSoejima. If this is still a problem, please open an issue in the beats repo, where this will actually get fixed.

**Comment by TomonoriSoejima** [comment]
`event.action` is seen in the doc https://www.elastic.co/guide/en/beats/auditbeat/6.4/exported-fields-common.html, but not any more in the current version https://www.elastic.co/guide/en/beats/auditbeat/current/exported-fields-common.html.

Thus I think the issue is no longer relevant and it can stay closed for good!
