### ISSUE TITLE
[beats][metricbeat][ml] Duplicate doc page for ml_job metricset

### ISSUE THREAD

**Issue by GlenRSmith** [elastic/docs#510]
The page
https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-elasticsearch-ml_job.html
seems to be an accidental stub.
The page
https://www.elastic.co/guide/en/beats/metricbeat/current/_elasticsearch_ml_job_metricset.html
appears to be the necessary doc.
Thanks.

**Comment by dedemorton** [comment]
@GlenRSmith The docs repo is for issues related to our documentation infrastructure. I've opened an issue for this in the beats repo: https://github.com/elastic/beats/issues/9880
