### ISSUE TITLE
Need to elaborate on the version conflict error 

### ISSUE THREAD

**Issue by jkelastic** [elastic/docs#524]
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html

The documentation should also include 

This warning is for a document that had no changes. Any other documents with changes will still get updated during this warning, source version <= destination, missing documents will get created." 

I didn't use "conflicts": "proceed", got

      "id": "HSaTemcBUPODKO5X5YBO",
      "cause": {
        "type": "version_conflict_engine_exception",
        "reason": "[test][HSaTemcBUPODKO5X5YBO]: version conflict, current version [4] is higher or equal to the one provided [1]",
        "index_uuid": "KCYr7WiDQIOnQK3XhFFgOw",
        "shard": "4",
        "index": "new_twitter"
      },
      "status": 409

My documents still got updated. From my testing it looks like we can ignore the warning.

**Comment by nik9000** [comment]
I believe this request should be on the Elasticsearch repository. This repository is just for building the docs.
