### ISSUE TITLE
Add destructive overwrite warning and/or directory creation to --out, 

### ISSUE THREAD

**Issue by palecur** [elastic/docs#55]
Currently, if the directory specified in --out contains anything, it is silently blown away. This behavior is fine when --out is unspecified, since it creates the new directory html_docs (or silently nukes the contents if that directory exists), but it also means that a casual error (specifying --out /some/dir, expecting it to result in /some/dir/html_docs instead of a nuked /some/dir with docs in it) can be really quite destructive.

**Comment by clintongormley** [comment]
The help page tells you that it will destroy that directory
