### ISSUE TITLE
Comments in tables are shown in output

### ISSUE THREAD

**Issue by lcawl** [elastic/docs#554]
If you have a comment in a table, for example:

> |=======================
> | Field               | Description
> | X       | Y
> //|comment1 |comment2                        
> |=======================

The  second row appears in the output, despite being commented out.
There are no errors or warnings and it's not clear if this is new or changed behaviour.

If it's expected behaviour, we should try to find all such occurrences and clean them out of our documentation.

**Comment by nrichers** [comment]
Since commenting out doesn't work, I did some testing with conditional coding and is a viable workaround. The following works just fine, even if it is a bit more cumbersome: 

```
ifeval::["{feature-flag}"=="no"]
|comment1 |comment2
endif::[]  
```

(Strange that a comment doesn't get processed correctly when an `ifeval` will, but there you go. 🙂 )

**Comment by gtback** [comment]
I'm not sure if this was an asciidoc.py thing, but I can't reproduce this when adding the example above to README.asciidoc in this repo. Maybe it was fixed in Asciidoctor? @lcawl can you check and see if this is still happening?

**Comment by lcawl** [comment]
Agreed, I can't replicate this problem anymore either.
