### ISSUE TITLE
Docker based build issue tracking

### ISSUE THREAD

**Issue by nik9000** [elastic/docs#591]
Some of you may know that we use an end of life tool, [AsciiDoc][], to build
all of our documentation. Back in 2017 they declared they'd stop releasing
updates and we've been stuck ever since. I've undertaken a project to migrate
us from that tool to an actively developed one, [Asciidoctor][]. Since it has
different dependencies I've taken the advice of my new colleagues at infra to
manage those dependencies with docker. And I'd like some beta-tester/victims to
try out the docker based build.

To build the docs the newfangled docker way you make sure you have docker
installed and then run your usual `build_docs.pl` command but without the
`.pl`. So if you are used to running

```
~/Code/Elastic/docs/build_docs.pl --doc ~/Code/Elastic/kibana/docs/index.asciidoc --chunk 1 --out ~/Code/Elastic/built_docs/ --open --lenient
```

then you can use docker for the build by running

```
~/Code/Elastic/docs/build_docs --doc ~/Code/Elastic/kibana/docs/index.asciidoc --chunk 1 --out ~/Code/Elastic/built_docs/ --open --lenient
```

All of the usual arguments to `build_docs.pl` *ought* to work with the exception
of `--all` on macOS. I'm still [fighting][] with that but not so many people
use it and I'm already in contact with them. If you have any issues with the
docker based build please report them at the [tracking issue][] on github.

IMPORTANT: Just using the docker based build doesn't switch you from AsciiDoc
to Asciidoctor. You *can* use Asciidoctor by adding `--asciidoctor` to the
command line arguments and some books build fine with it but not all of them
do. I have an [asciidoctor tracking issue][] as well, but I that is a lot
further from being done. Feel free to try it though!

ALSO SORT OF IMPORTANT: The docker based build is fairly "simple" and put
together with as few moving parts as I could manage. I'd prefer to delay a
docker purity religious war at this stage. I'm happy to make improvements along
those lines later but I'm trying for progress over perfection here. Especially
when perfection has a few diametrically opposed definitions. If none of that
makes any sense to you then great! It is like the EMACS vs VI debate but with
docker instead. And I picked nano, probably upsetting all sides.

[AsciiDoc]: https://github.com/asciidoc/asciidoc/releases/tag/8.6.10
[Asciidoctor]: https://asciidoctor.org/
[fighting]: https://github.com/elastic/docs/pull/589
[tracking issue]: https://github.com/elastic/docs/issues/591
[asciidoctor tracking issue]: https://github.com/elastic/docs/issues/505

**Comment by dedemorton** [comment]
Ran into errors after running the command several times. The sequence I followed was:

1. Ran the command I normally use with .pl omitted. Resulted in an error, maybe because the alias I have set up is 3 years old and uses a slightly different syntax (`--chunk=1 -open`) with no output directory specified. Saw the following error:

````
NFO:build_docs:nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (2: No such file or directory)
INFO:build_docs:2019/02/09 00:13:53 [emerg] 109#109: mkdir() "/var/lib/nginx/body" failed (30: Read-only file system)
````
2. Fixed the command syntax and ran build_docs successfully (no errors).
3. Ran the command on a different book (perhaps with a command line syntax error--not sure), and saw the following error:

````
INFO:docker build:Building the docker image that will build the docs. Expect this to take somewhere between a hundred milliseconds and five minutes.
INFO:build_docs:docker: Error response from daemon: driver failed programming external connectivity on endpoint clever_curie (99dd3201885a4872884c18e51318aebe67b8bb7bdce5719989d8805d957612bc): Bind for 0.0.0.0:8000 failed: port is already allocated.
````

I was able to kill the docker container and get things running again, but I'm not sure what caused the problem or whether other folks are likely to encounter it.

**Comment by lcawl** [comment]
The Stack Overview fails too. For example: 

>docs/build_docs --doc $GIT_HOME/stack-docs/docs/en/stack/index.asciidoc --resource=$GIT_HOME/kibana/docs --resource=$GIT_HOME/elasticsearch/docs --resource=$GIT_HOME/elasticsearch/x-pack/docs --chunk 1 --out built_docs/ --lenient --open
INFO:docker build:Building the docker image that will build the docs. Expect this to take somewhere between a hundred milliseconds and five minutes.
INFO:build_docs:Old PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
INFO:build_docs:New PATH=/docs_build/resources/asciidoc-8.6.8:/docs_build/resources/asciidoctor/bin:/docs_build:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
INFO:build_docs:Building HTML from /doc/docs/en/stack/index.asciidoc
INFO:build_docs:
INFO:build_docs:
INFO:build_docs:asciidoc: WARNING: index.asciidoc: line 17: include file not found: /doc/docs/en/stack/../../../../elasticsearch/x-pack/docs/en/security/authentication/custom-realm.asciidoc
INFO:build_docs:asciidoc: WARNING: index.asciidoc: line 20: include file not found: /doc/docs/en/stack/../../../../elasticsearch/x-pack/docs/en/security/authentication/anonymous-access.asciidoc
INFO:build_docs:asciidoc: WARNING: index.asciidoc: line 23: include file not found: /doc/docs/en/stack/../../../../elasticsearch/x-pack/docs/en/security/authentication/user-cache.asciidoc
INFO:build_docs:asciidoc: WARNING: index.asciidoc: line 26: include file not found: /doc/docs/en/stack/../../../../elasticsearch/x-pack/docs/en/security/authentication/saml-guide.asciidoc
INFO:build_docs:asciidoc: WARNING: index.asciidoc: line 9: include file not found: /doc/docs/en/stack/../../../../elasticsearch/x-pack/docs/en/security/authorization/managing-roles.asciidoc
INFO:build_docs:asciidoc: WARNING: index.asciidoc: line 21: include file not found: /doc/docs/en/stack/../../../../elasticsearch/x-pack/docs/en/security/authorization/alias-privileges.asciidoc
INFO:build_docs:asciidoc: WARNING: index.asciidoc: line 24: include file not found: /doc/docs/en/stack/../../../../elasticsearch/x-pack/docs/en/security/authorization/mapping-roles.asciidoc
...

I think it might be related to the extra "docs" folder, which does not align with the relative directories defined in https://raw.githubusercontent.com/elastic/stack-docs/master/docs/en/stack/index.asciidoc

**Comment by axw** [comment]
I just tested with the APM Go agent: https://github.com/elastic/apm-agent-go/pull/446. Apart from using `build_docs` instead of `build_docs.pl`, I just had to change `-out` to `--out`. Not to say that the new version should support both, but Perl's Getopt::Long will, by default, handle either `-out` or `--out`.

Other than that, I had no issues.

**Comment by nik9000** [comment]
> I just tested with the APM Go agent: [elastic/apm-agent-go#446](https://github.com/elastic/apm-agent-go/pull/446). Apart from using `build_docs` instead of `build_docs.pl`, I just had to change `-out` to `--out`. Not to say that the new version should support both, but Perl's Getopt::Long will, by default, handle either `-out` or `--out`.

I see @dedemorton ran into the same thing. It wouldn't be too difficult to add support for those and folks do use it so I'll have a look at that.

@dede: I'll check and see if the `-out` issue caused the second docker error that you see. I have to be very careful not to leave the docker container hanging and it looks like I've made a mistake somewhere. When this happens you can use `docker kill $(docker ps -aq)` to blast all running docker containers. You shouldn't have to but I'm not perfect so bugs'll happen from time to time.

@lcawl: I'll take a look at the stack overview. Getting all of the directories hooked up to work with `--doc` is pretty fiddly and I've likely made a mistake there.

**Comment by dedemorton** [comment]
Folks testing the docker build should make sure there is not a container running when they go back to using the Perl script. Otherwise --open will display whatever docker build they ran because docker still has the port open. 

They can run `docker container ls` to see if a container is running.

**Comment by nik9000** [comment]
> They will need to kill the container as described in the previous comment.

They *shouldn't* though. If it leaves a container running then I've made a mistake. Unless you just have it open in another window or something.

**Comment by nik9000** [comment]
@lcawl I think we *should* be fine with the stack overview now!

**Comment by nik9000** [comment]
@dedemorton and @axw, I've fixed up the docker build to explicitly reject single dashed arguments like `-doc` and point you to `--doc`. The perl script ought to continue to accept them for as long as continue using it.

**Comment by lcawl** [comment]
@nik9000 You're right.  The Stack Overview build works now.  Thanks!

**Comment by nik9000** [comment]
Since this issue isn't receiving a lot of feedback I'm going to close it. At this point I consider the docker based `build_docs` to be *the* way to build the docs. It isn't perfect but whenever we find issues I'm going to file them against the docs repo rather than group them here.
