### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by asbjornu** [elastic/docs#63]
When running `./build_docs.pl --all`, it tries (as configured in `conf.yaml`on line 75) to clone the repositories [found](/elastic/found.git) and [x-plugins](/elastic/x-plugins.git), which can't be found:

```bash
Updating repositories
 - Cloning beats from <https://github.com/elastic/beats.git>
 - Cloning curator from <https://github.com/elastic/curator.git>
 - Cloning elasticsearch from <https://github.com/elastic/elasticsearch.git>
 - Cloning elasticsearch-hadoop from <https://github.com/elastic/elasticsearch-hadoop.git>
 - Cloning elasticsearch-js from <https://github.com/elastic/elasticsearch-js.git>
 - Cloning elasticsearch-net from <https://github.com/elastic/elasticsearch-net.git>
 - Cloning elasticsearch-php from <https://github.com/elastic/elasticsearch-php>
 - Cloning found from <https://github.com/elastic/found.git>
Error updating repo <found>: Error executing: git clone https://github.com/elastic/found.git .repos/found
Cloning into '.repos/found'...
remote: Repository not found.
fatal: repository 'https://github.com/elastic/found.git/' not found
```

Are the repositories private or are they renamed to [found-shield-example](/elastic/found-shield-example) and [kibana-phoenix-plugin](https://github.com/elastic/kibana-phoenix-plugin), respectively?

**Comment by clintongormley** [comment]
They are private.  You don't need to run build with the `--all`  option, that's purely for deployment to the elastic docs

**Comment by asbjornu** [comment]
@clintongormley Ok. But is it another way to simply download all repositories to find the one in which to do corrections and then test it? Could the private repositories perhaps be skipped if you don't have access, so it doesn't just fail and exit?
