### ISSUE TITLE
Tooltips for links include trailing "edit" stolen from the edit icon

### ISSUE THREAD

**Issue by nik9000** [elastic/docs#641]
The tooltips for xref links include the word "edit" on the end, presumably stolen from the "edit" link. You can see it by heading [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/search.html) and searching for the first mention of the word "search cancelation". If you mouse over it, you'll see the tooltip is "Search Cancellationedit".

**Comment by nik9000** [comment]
That link doesn't seem to have the edit on the tooltip anymore. How odd!

**Comment by dmeiss** [comment]
Cool -- self-fixing issues! Maybe something changed after website redesign went live?

**Comment by nik9000** [comment]
> Cool -- self-fixing issues! Maybe something changed after website redesign went live?

I greped around and didn't see it. But I'm pretty sure I did something wrong.....

**Comment by gtback** [comment]
I'm also not able to find any examples of this with some fancy grepping, so I'm going to close this. We can re-open if it happens again.
