### ISSUE TITLE
Feature: inject metadata into head section

### ISSUE THREAD

**Issue by AnneB-SEO** [elastic/docs#655]
Per our meeting today (2/27/2019) with: @debadair @nik9000 @nrichers @sylvie777 @liztauscher 

We'd like a feature that will enable the Docs Team to inject a robots meta tag into the docs HTML head section for pages that will be removed. This will allow us to remove content from the Google search index, which cannot be done once the page is deleted. 

Related document: [How to Remove Content from the Google Search](https://docs.google.com/document/d/1dKRDqvGulzGPLwG6Ycj8bEA_Xktj29fLzwdLw0huROs/edit?usp=sharing)

**Comment by AnneB-SEO** [comment]
Hi @nik9000 - Any update on this ticket?

**Comment by nik9000** [comment]
I haven't started and probably won't until I finish with the Asciidoctor conversion which is a few months out I think.

**Comment by debadair** [comment]
With the Asciidoctor migration complete, it is now possible to use the `keywords` and `description` attributes to inject metadata for a page. We can also inject custom attributes such as the robots meta tag using docinfo files:

1. Create a `docinfo.html` file that contains the meta tag:

    ```<meta name="robots" content="noindex,nofollow”/>```

2. Add the docinfo attribute to the page. For example:

    ```
    :docinfo: shared
    ["appendix",role="exclude",id="redirects"]
     = Deleted pages```
I was not able to get per-page "private" doc info files to work, but setting the `docinfodir` attribute worked & could be used to differentiate between the shared robots tags and other uses of docinfo. 

Closing this feature issue as complete, but this relates to #1820.
