### ISSUE TITLE
Universal docs testing for PRs

### ISSUE THREAD

**Issue by nik9000** [elastic/docs#670]
Right now every team at Elastic uses its own process for testing that their docs changes are good. These processes are unique and wonderful but they all tend to leave something out. For example, the Elastsicsearch team builds the Elasticsearch reference as part of every PR. But there are a dozen "books" that the Elasticsearch repository is involved in and it doesn't build those. This lets things slip through the cracks from time to time. The Elasticsearch team uses `doc_build_aliases.sh` which is nice because it gives the docs team a central place to control the commands used to build the docs. Other teams do not do this so they are likely to "drift" from the canonical way to build docs. There are many repos involved with docs that don't have PR testing at all because it is time consuming to maintain the list of all of the docs to build.

I've started building (#659) some infrastructure for testing all of the books for any repository. We should be able to build on this to test docs changes in any PR. My plan at the moment is to add PR testing for some repositories that don't already have it once we have #659 and see how those shake out for a few weeks. From there I think we could shift a real team to PR testing.

**Comment by lcawl** [comment]
I think this is a known issue, but the elasticsearch-ci/docs-build checks in PRs e.g. https://github.com/elastic/stack-docs/pull/373 seem to be out-dated sometimes. i.e. they're not pulling the latest info for their link checks.

**Comment by nik9000** [comment]
> I think this is a known issue, but the elasticsearch-ci/docs-build checks in PRs e.g. [elastic/stack-docs#373](https://github.com/elastic/stack-docs/pull/373) seem to be out-dated sometimes. i.e. they're not pulling the latest info for their link checks.

I believe we've *mostly* fixed this by always forking the built docs from master and by merging the target branch into the PR before building the docs.

Merging the target branch into the PR branch has caused another interesting failure mode: if there are changes to two repos that require one another and both are merged at the same time then PR tests touching either repo will fail until the docs build. This *sounds* rare, but it is something we do fairly frequently.

**Comment by nik9000** [comment]
* [x] elastic/apm-server.git
* [x] elastic/apm-agent-nodejs.git
* [x] elastic/apm-agent-python.git
* [x] elastic/apm-agent-ruby.git
* [x] elastic/apm-agent-rum-js.git
* [x] elastic/apm-agent-go.git
* [x] elastic/apm-agent-java.git
* [x] elastic/apm-agent-dotnet.git
* [ ] elastic/azure-marketplace.git
* [ ] elastic/beats.git
* [ ] elastic/cloud.git
* [ ] elastic/curator.git
* [ ] elastic/ecs.git
* [ ] elastic/elasticsearch-hadoop.git
* [x] elastic/elasticsearch-js.git
* [ ] elastic/elasticsearch-ruby.git
* [ ] elastic/elasticsearch-net.git
* [ ] elastic/elasticsearch-php
* [x] elastic/elasticsearch.git
* [ ] elastic/elasticsearch-definitive-guide.git
* [ ] elastic/kibana.git
* [ ] elastic/logstash.git
* [ ] elastic/logstash-docs.git
* [ ] elastic/sense.git
* [x] elastic/stack-docs.git
* [ ] elastic/swiftype-doc-placeholder.git
* [x] elastic/x-pack.git
* [ ] elastic/x-pack-elasticsearch.git
* [ ] elastic/x-pack-kibana.git
* [ ] elastic/x-pack-logstash.git
* [x] elastic/cloud-on-k8s.git
* [ ] elasticsearch-cn/elasticsearch-definitive-guide.git
* [ ] elasticsearch-cn/elasticsearch-php.git
* [ ] elasticsearch-cn/kibana.git

**Comment by nik9000** [comment]
* [x] elastic/apm-server.git
* [x] elastic/apm-agent-nodejs.git
* [x] elastic/apm-agent-python.git
* [x] elastic/apm-agent-ruby.git
* [x] elastic/apm-agent-rum-js.git
* [x] elastic/apm-agent-go.git
* [x] elastic/apm-agent-java.git
* [x] elastic/apm-agent-dotnet.git
* [ ] elastic/azure-marketplace.git
* [ ] elastic/beats.git
* [ ] elastic/cloud.git
* [ ] elastic/curator.git
* [ ] elastic/ecs.git
* [ ] elastic/elasticsearch-hadoop.git
* [x] elastic/elasticsearch-js.git
* [ ] elastic/elasticsearch-ruby.git
* [ ] elastic/elasticsearch-net.git
* [ ] elastic/elasticsearch-php
* [x] elastic/elasticsearch.git
* [ ] elastic/elasticsearch-definitive-guide.git
* [ ] elastic/kibana.git
* [ ] elastic/logstash.git
* [ ] elastic/logstash-docs.git
* [ ] elastic/sense.git
* [x] elastic/stack-docs.git
* [ ] elastic/swiftype-doc-placeholder.git
* [x] elastic/x-pack.git
* [ ] elastic/x-pack-elasticsearch.git
* [ ] elastic/x-pack-kibana.git
* [ ] elastic/x-pack-logstash.git
* [x] elastic/cloud-on-k8s.git
* [ ] elasticsearch-cn/elasticsearch-definitive-guide.git
* [ ] elasticsearch-cn/elasticsearch-php.git
* [ ] elasticsearch-cn/kibana.git

**Comment by nik9000** [comment]
One thing I think we'd like is better reporting in the github status field: we should say "no changes" if the build generated the same bits. We should say "preview at <link>" if we made a preview.

**Comment by nik9000** [comment]
We probably should also modify the preview application's 404 page to say that noop changes don't generate a diff. We could probably explain quite a few things on the 404 page.

**Comment by nik9000** [comment]
I've strike-through-ed the deprecated repositories above. I don't think we'll add tests to them.

**Comment by gtback** [comment]
This is being tracked for cloud (the one remaining repo) in another place.
