### ISSUE TITLE
Dates in sitemap.xml

### ISSUE THREAD

**Issue by nik9000** [elastic/docs#684]
Right now every time we generate new docs we rebuild the `sitemap.xml` setting every file to last edited "now". This makes our diffs pretty big and isn't really true. I wonder if it'd be ok if didn't bump the time if we didn't rebuild the book.

**Comment by brianjolly** [comment]
@AnneB-SEO, can you let us know the latest on how important / unimportant `lastmod` is in the sitemap? Maybe it could only bump the date for new releases?

**Comment by AnneB-SEO** [comment]
@brianjolly & @nik9000 Per Google, the 2 most important fields in the XML sitemap are 1) URL and 2) last modified date. It makes sense to only change the date for new books (which I will assume equates with rebuilding the book ?). This approach might help our ranking for new releases - we might be able to see that over time yet it could be hard to measure. Thx!

**Comment by nik9000** [comment]
I sounds to me like making the dates track better to when we actually change the books will either help SEO stuff or do nothing. Since I want to make the change for non-SEO reasons I'm happy to hear that!

**Comment by AnneB-SEO** [comment]
Yes, it's a win-win! So glad you are able to make a change like that
