### ISSUE TITLE
Make doc images autoscale

### ISSUE THREAD

**Issue by palecur** [elastic/docs#70]
Currently, images in the docs display at their original resolution, unlike images in blogs, which are responsive to screen size. Block images should render into HTML with the `class="img-responsive"` attribute. Inline images should stay as they are.

**Comment by clintongormley** [comment]
Can you give me an example where the current CSS for images is not working correctly?  eg see the images on https://www.elastic.co/guide/en/elasticsearch/reference/2.1/query-dsl-function-score-query.html#exp-decay - these resize as you resize the screen width.

**Comment by palecur** [comment]
https://www.elastic.co/guide/en/kibana/current/setup.html (image attached)


​
