### ISSUE TITLE
Search suggestion list contains links to files in an old branch 

### ISSUE THREAD

**Issue by dedemorton** [elastic/docs#72]
Go to https://www.elastic.co/guide/index.html.
Click the Search icon.
Start typing rotate_every_kb.
In the suggestion list, click the first link (for Filebeat).
You see a 404 error because the link points to https://www.elastic.co/guide/en/beats/filebeat/1.0.0/filebeat-configuration-details.html#_rotate_every_kb, but the 1.0.0 branch was removed.

Not sure if this is related to issue #59 or what. This is all just so magical....

**Comment by clintongormley** [comment]
The suggester was using the searchdev URL instead of the main search URL  This has been fixed
