### ISSUE TITLE
Add link to subscriptions page via post-processing

### ISSUE THREAD

**Issue by lcawl** [elastic/docs#720]
The X-Pack icon near page or section title is currently implemented as described in https://github.com/elastic/docs/issues/542

We would like to turn it into a link to https://www.elastic.co/subscriptions

I had intended to accomplish this via the following Asciidoctor functionality: https://github.com/elastic/docs/pull/567 but the last time I tested it, there were problems: https://github.com/elastic/docs/issues/505#issuecomment-459163236

If we can accomplish this temporarily (or permanently) via post-processing instead, that's worth considering.

**Comment by lcawl** [comment]
It seems to me that for the post-processing to work, we would either need to:

- Implement this similar to the current edit-me links (though in this case it would use the same URL in all the Stack docs and instead of disabling infrequently (:edit_url!:) we'd likely want its default to be disabled since the OSS-specific pages typically out-number the X-Pack-specific pages.

- Add an element to each X-Pack-specific page/section that can be post-processed to be a clickable image (i.e. by turning it into something like `<a href="https://www.elastic.co/subscriptions" class="license_me" title="Link to subscriptions" rel="nofollow">Subscriptions</a>`).

In both cases you'd need to add something like this to the style.css (based on the existing edit_me and xpack examples):

>#guide a.license_me {
    position: absolute;
    font-size: 14px;
    right: -15px;
    top: 0;
    text-align: center:
    z-index: 1000;
    padding-top: 26px;
    line-height: 1;
    opacity: 0.3;
    background-repeat: no-repeat;
    background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAUCAYAAADPym6aAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAARTQAAEU0BwDlgYwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAQfSURBVEiJ3VdbaBxlGD3fP5PtTqxBjYhYxCRqNAFtMZs3sQar0ezMThthEMFWVJBUUFpsY1NLg7RgHytSbAreQKQTarLzz24CiiNeXxKDWm2MD1KFtVIV4u6615nPh2YhLNmtiYW1HhiY+a7nzM+BGbJtW9E0bR8RPcnMbbi88Aszn8zn8yOqpmn7AOwC8CIR/dBoZqsBM99ARIc0TbtCBfAUgP26rr/WaGJrgeM454loQgC4CcB8owmtFb7vnwGwTjSayKWCWisRj8dvE0J0GoYhK7FkMrnO9/3Hcrnc25ZlFZfXT05O3qiq6kNLjwVmXjAM44t/Q05KmQ2FQtf19/dnL1Zb70RSAI46jtNbCQRBMAJgU7UIAFAU5Q5mHgZwNTPfDuCYlDLheV7Nl3UpUXOJaZrpRCKxMwiCMc/zehcXFzuZ+ZFcLtdTZ95Puq4fAQDbtg9qmjafTqfvAfAhADiO005EHcx8LhaLfbu8cXp6+ppyubzR9/1iS0vLbF9fX3553vM8NZvNbhRCnB4YGChUL67rkWg0Og3g60wms1tRlONE9IxlWZl6PRVYllVk5p+JqAUApJTPEdEJADEiekdKeaRS6zjOw6VSaS4IgieEEHuz2ezW5bNGR0dFOp1+g5kfXUkEUOdEKmhqatpVKpXmAUzruv7BPxHBzOS6rgngVkVRPgMAXddfIaKjwAU/KYoyC2DYtu31RHSMiO41DOPMSvN6enpeJaJsNBp9vtbOiwopl8vtAP4CcJdt2yHLsoq2bSvNzc2DSyW+ruvvLd3fLaX8w3XdPwF8A0AfGBg4DwDj4+NNruvez8y3ALhq6UI4HO4C8Kuu6yuKKJVKewF0zszMPKDrOq9JiOd5aiaTGRNCbA+CYEc4HH4BwEsdHR0ilUptAQAiKgGoCPnUMIy+6jlSymsBfMLME8z8uRAiy8z7AUAIsZ6Zc7U4MHM7gK5IJNIN4PSahGQymd1ENBeNRj+WUn5HRF9JKe1IJDIP4Ol6vVW4D8BZwzBGACAej98pxAV7+r7/vRCiMx6PX2maZrq6MRQKDRUKhQcBjNu23VvLozXNnkwmbwaws1gsDgOAYRi/ATgIYIyZaRUiEATBAoBNruvGpJTbhBCHAeQBwDTNFBGdFEKMSym3SSm3O46zeXl/LBY7xczva5p2vNaOmkJ8329j5h2Dg4O/V2Kzs7OvAzg1NTW1obqeiOaZeWylWaZpzgkhHg+CYAsRdSmKMsTMz1by0Wh0iIjeBLCZmbuZ+dxS6kBra2sRAFRV3UNEXyYSietX2kFSSgbQZxjGR7VE/ZcxMTHRpqrqj/+bby0B4CwRdTWayFqhqmo3gILKzCcAHHYch4QQC40mtkpsYOZDzPyWms/nX9Y0LRBC7LkMf3VTAN7N5/MH/gYB17/KZ7ITXwAAAABJRU5ErkJggg==');
}

> #guide a.license_me:hover {
    opacity: 1;
}

**Comment by nik9000** [comment]
I'm working on this now. I've got a link showing up in the page but there is javascript getting in the way. I'll keep working on it!

**Comment by lcawl** [comment]
@nik9000 Here are some examples of the use of the icon inline:
https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-node.html#ml-node
https://www.elastic.co/guide/en/kibana/master/working-remote-clusters.html#managing-cross-cluster-replication

**Comment by nik9000** [comment]
Thanks!
