### ISSUE TITLE
Shield docs online out of date

### ISSUE THREAD

**Issue by robin13** [elastic/docs#74]
It looks like this was already corrected in the repository on `2015-10-27`, but the install section [here](https://www.elastic.co/guide/en/shield/current/installing-shield.html) is still showing to use `-i` rather than `install`

Is something broken with the automatic publishing for shield docs?

**Comment by clintongormley** [comment]
It was fixed in master, not in 2.1.  please open an issue on the shield repo

**Comment by robin13** [comment]
Done: https://github.com/elastic/x-plugins/issues/1305
