### ISSUE TITLE
Build documentation directly to HTML; eliminate DocBook step

### ISSUE THREAD

**Issue by lcawl** [elastic/docs#743]
After our migration to Asciidoctor is complete, there are features we cannot use due to the fact that we still convert to DocBook then HTML. The features don't seem to generate errors or warnings, they just don't work. For example:

- https://github.com/elastic/docs/issues/726
- ~https://github.com/elastic/docs/issues/896~
- https://github.com/elastic/docs/issues/1279

Per https://github.com/elastic/docs/issues/249#issuecomment-343424353 "Docbook output is required as the asciidoctor html output doesn't support html chunking, plus docbook gives us strict link checking. It would still be a big speedup. That said, I don't know about the difference in output and error checking behaviour. Plus the customizations need to be ported over. This is a huge undertaking..."

This issue is intended to collect a list of the features that don't work in the current implementation and ideas about how we could eliminate the need for Docbook.

**Comment by nik9000** [comment]
I'm going to pick this up soon!

**Comment by nik9000** [comment]
I think we've actually finish this. I removed docbook from the docs repo entirely in January.
