### ISSUE TITLE
Problem with callouts in tagged regions

### ISSUE THREAD

**Issue by lcawl** [elastic/docs#755]
The callouts in the example on this page in the Elasticsearch Reference work:
https://www.elastic.co/guide/en/elasticsearch/reference/7.0/breaking-changes-7.0.html#_literal_track_total_hits_literal_defaults_to_10_000

When that content is re-used in the Installation and Upgrade Guide (https://github.com/elastic/elasticsearch/pull/40478), however, the callouts get messed up as follows:
![image](https://user-images.githubusercontent.com/26471269/55089614-e75e8e80-506a-11e9-84dd-13fa6866ee31.png)

**Comment by lcawl** [comment]
I've tried removing the //NOTCONSOLE, but that doesn't affect the problem.

**Comment by nik9000** [comment]
Weird!

**Comment by gtback** [comment]
@lcawl is this still a problem? It looks like the example you're pointing to (https://www.elastic.co/guide/en/elastic-stack/7.0/elasticsearch-breaking-changes.html) is working now. Maybe it was an asciidoc.py thing that was fixed by asciidoctor?

**Comment by lcawl** [comment]
Agreed, the callouts look fine in https://www.elastic.co/guide/en/elastic-stack/7.0/elasticsearch-breaking-changes.html now
