### ISSUE TITLE
Attributes not resolved in abbreviated titles

### ISSUE THREAD

**Issue by lcawl** [elastic/docs#760]
This problem was found while testing https://github.com/elastic/docs/pull/756 and https://github.com/elastic/docs/pull/649

![image](https://user-images.githubusercontent.com/26471269/55179610-10ebe880-5145-11e9-89d7-55c90c4395c5.png)

The source file for this occurrence is https://github.com/elastic/stack-docs/blob/master/docs/en/stack/watcher/troubleshooting.asciidoc 

````
++++
<titleabbrev>{watcher}</titleabbrev>
++++
````

A simple solution might be to just remove all these abbreviated titles.

**Comment by nik9000** [comment]
I > The latest test shows a similar error that I reported in #756. See #760

I think the asciidoctor [approved](https://asciidoctor.org/docs/user-manual/#pass-blocks) fix is to add

```
[subs=attributes]
```
 
above it. If this is pretty rare I think we should probably just do that all of the places we use this.

**Comment by lcawl** [comment]
That solves the problem in the Asciidoctor output, but it generates the following error in the non-Asciidoctor build:

> ERROR ... illegal style name: subs=attributes

**Comment by nik9000** [comment]
How do you feel about `[subs="attributes"]`?

**Comment by lcawl** [comment]
Good catch, that seems to work for both.  Thanks!

**Comment by debadair** [comment]
Closing as fixed.
