### ISSUE TITLE
Link to "How to install license" necessary in Watcher 

### ISSUE THREAD

**Issue by robin13** [elastic/docs#78]
In the watcher docs (both 1.x and 2.x) the instruction notes:

> You need to install the License and Watcher plugins on each node in your cluster.

... and gives instructions how to install the license plugin, but not how to install the actual license.  I have been asked several times by customers "is that all, what about the license json file you sent me?" or worse still "my (test) license has expired!".

Would it be possible to have a link to licence installation documentation here?

**Comment by robin13** [comment]
Links:
https://www.elastic.co/guide/en/watcher/watcher-1.0/getting-started.html
https://www.elastic.co/guide/en/watcher/current/getting-started.html

**Comment by debadair** [comment]
Opened issue in x-plugins repo: https://github.com/elastic/x-plugins/issues/1450
