### ISSUE TITLE
Adding a "deprecated" warning to old docs?

### ISSUE THREAD

**Issue by jpountz** [elastic/docs#8]
Some documentation pages from old versions are indexed by Google, and when you land to such a page it might not be obvious that this documentations refers to an old version. I have had this issue once or twice and apparently some users have the same issue: https://twitter.com/saidimu/status/586571547420323840

When we move to a new major version maybe we should have a way to add a header to all documentation pages from the previous version to let users know that they are not reading documentation from the most recent version of elasticsearch?

**Comment by clintongormley** [comment]
Closed by https://github.com/elastic/docs/commit/78d3a99bd2e3d5ce3eca2ba01696f6e12de66732
