### ISSUE TITLE
Add ability to generate overview links in container topics

### ISSUE THREAD

**Issue by dedemorton** [elastic/docs#82]
Right now, our docs have "container" topics that are used to group related topics (see example below). Some of them have intro text and some do not. I've heard from a couple of internal users who thought there was content missing from the topic because they didn't notice that there were sub-topics.

In general, it's pretty common to have container topics in docs, but the way our TOC is positioned on the page, it's not always obvious that there are sub-topics. When the container topic is short and appears towards the middle or end of the TOC, you don't even see the part of the TOC that pertains to the topic (see example below). 

We can manually fix this problem by adding a list of links to the container topic itself. However, this becomes a maintainability issue when doc gets moved around, deleted, or added. It would be really nice if we had a way for the doc build to automatically generate links and add them to topics that we've identified as container topics. We would not want links to be generated for all topics that have sub-topics, just the ones that we identify.

Example of container topic:
![docstructure](https://cloud.githubusercontent.com/assets/14206422/13856764/f93ef94e-ec33-11e5-8b55-31a3cfc19f56.png)

@ruflin FYI

**Comment by clintongormley** [comment]
Honestly, I think this is something that should be handled on a case-by-case basis, by writing some content.

**Comment by dedemorton** [comment]
@clintongormley The example that I gave def needs content, but that's a separate issue. The container topics in the Beats doc do contain short descriptions, but people have told me that it looks like content is missing from the doc. Here's an example:

https://www.elastic.co/guide/en/beats/filebeat/current/reference.html

With the shorter container topics, users can't always see the part of the TOC that's relevant to the topic they're looking at (without scrolling down), so they lack context for what the section contains, and topic just looks odd to them.

**Comment by clintongormley** [comment]
@dedemorton Sure, but that's just because the intro text is insufficient.

There's really no way to add filler text automatically - it requires doing something like I've done on these pages:

* https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html
* https://www.elastic.co/guide/en/elasticsearch/reference/current/full-text-queries.html
* https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html
* https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-types.html

**Comment by dedemorton** [comment]
@clintongormley Thanks for explaining the limitation. I've worked with tools in the past (like DITA XML) where you get all the overview links and short descriptions generated for you, and it make maintaining the doc over time _much_ easier. But I guess you gotta dance with the one who brought you. :-)
