### ISSUE TITLE
Include release highlights for Cloud

### ISSUE THREAD

**Issue by KOTungseth** [elastic/docs#823]
We would like to add Elastic Cloud Enterprise and Elasticsearch Service to the [Highlights](https://www.elastic.co/guide/en/elastic-stack/current/elastic-stack-highlights.html) and [Breaking changes](https://www.elastic.co/guide/en/elastic-stack/current/elastic-stack-breaking-changes.html). 

Since Elasticsearch Service releases every three weeks, this might get tricky when deciding how to pull from the `release-ms-x` branches. 

Also, ECE does not follow the same branch scheme as the rest of the Stack, but it has been following the same release schedule.

**Comment by lcawl** [comment]
@nik9000 Would it be possible to have an option in the https://github.com/elastic/docs/blob/master/conf.yaml that accomplished something like this?:

>            title:      Installation and Upgrade Guide
>             ...
>            sources:
>             -
>                repo:   cloud
>                path:   docs/cloud-enterprise
>                map_branches:  [ 7.0=2.2, 6.7=2.1, ... ]

**Comment by nik9000** [comment]
I'm not entirely sure I understand the problem so I'm going to say what I think it is. Please tell me if I have it right.

When we build book we build them using the same branch for all repos. But you want to use a different branch name for *some* repos. That'd let us merge release notes from Cloud and the stack so long as we're ok picking some cloud branch that is "close" to the stack branch. The book would still be versioned with the stack.

**Comment by lcawl** [comment]
That's right @nik9000. It would enable us to use tagged regions from the cloud repos in other books.

**Comment by nik9000** [comment]
I think I can do that!

**Comment by nik9000** [comment]
I think I did that!

**Comment by nik9000** [comment]
It doens't look 100% the same. It should work like:
```
       title:      Installation and Upgrade Guide
        ...
       sources:
        -
           repo:   cloud
           path:   docs/cloud-enterprise
           map_branches:  { 7.0: 2.2, 6.7=2.1, ... }   <---- you can write this as a normal yaml object if you want too
```
