### ISSUE TITLE
6.7.2 Release

### ISSUE THREAD

**Issue by debadair** [elastic/docs#829]
PRs for version bumps & RNs:

Shared versions: https://github.com/elastic/docs/pull/828
ES versions: https://github.com/elastic/elasticsearch/pull/41422
ES RNs: https://github.com/elastic/elasticsearch/pull/41297/files (merged)

ECE RNs: https://github.com/elastic/cloud/pull/31477
ESS RNs: https://github.com/elastic/cloud/pull/31486

APM RNs & version bump: https://github.com/elastic/apm-server/pull/2135

Logstash RNs: https://github.com/elastic/logstash/pull/10692
Logstash doc version bump: https://github.com/elastic/logstash/pull/10703 

Beats doc version bump: https://github.com/elastic/beats/pull/11898 
Beats RNs: (merged) https://www.elastic.co/guide/en/beats/libbeat/6.7/release-notes-6.7.2.html

Kibana RNs: (merged) https://www.elastic.co/guide/en/kibana/6.7/release-notes-6.7.2.html

**Comment by schersh** [comment]
Kibana RN for 6.7.2 are published with the “coming” tag
