### ISSUE TITLE
Doc build no longer workes on a clone of your fork

### ISSUE THREAD

**Issue by dedemorton** [elastic/docs#845]
Doc build no longer works if you clone your fork.

Some folks prefer to clone their forks (rather than the elastic repo), but the doc build no longer accommodates that workflow. It expects an elastic repo. If you try to build the docs from a clone of your fork, you see something like:

```
Rhodas-MBP:stack-docs⎇ master$ docbldgke --open
INFO:docker build:Building the docker image that will build the docs. Expect this to take somewhere between a hundred milliseconds and five minutes.
INFO:build_docs:Building HTML from /doc/stack-docs/docs/en/gke-on-prem/index.asciidoc
INFO:build_docs:Couldn't find edit url because there isn't an Elastic clone
INFO:build_docs:origin	git@github.com:dedemorton/stack-docs.git (fetch)
INFO:build_docs:origin	git@github.com:dedemorton/stack-docs.git (push)
INFO:build_docs:
INFO:build_docs:asciidoctor: WARNING: gke-on-prem-introduction.asciidoc: line 2: couldn't find edit url for /doc/stack-docs/docs/en/gke-on-prem/gke-on-prem-introduction.asciidoc
```

I'm not sure whether we want to support this workflow, but I know that some people prefer to work out of their cloned forks to keep their forks up-to-date.

@DanRoscigno FYI

**Comment by dedemorton** [comment]
Closing because I realized after the fact that the dependency is simply that you need to have a remote that points to the elastic repo. So it doesn't matter if you've cloned the fork or the elastic stack-docs repo.

**Comment by nik9000** [comment]
I think this *should* work even if not many folks will need it.
