### ISSUE TITLE
Elasticsearch settings missing in docs

### ISSUE THREAD

**Issue by crisdarocha** [elastic/docs#849]
Settings like "xpack.watcher.internal.ops.index.default_timeout" are missing in our documentation.

For example, this specific setting, in it's old version ("watcher.internal.ops.index.default_timeout") can be found in this old page (https://www.elastic.co/guide/en/watcher/current/configuring-default-internal-ops-timeouts.html, which you can reach coming from the general page that explains the settings (https://www.elastic.co/guide/en/watcher/current/actions.html#actions-index).

The new version (with "xpack.") doesn't have a counter part in the docs.

The general pages about the settings (https://www.elastic.co/guide/en/elastic-stack-overview/current/actions-index.html describe the feature, but doesn't tell you the setting to put in elasticsearch.yml to actually use this feature.

Also, unfortunately, not an isolated issue.

Thanks a lot.

**Comment by nik9000** [comment]
@crisdarocha, this repository is for the infrastructure to build the docs rather than issues with the docs themselves. This'd do better as an issue in github.com/elastic/elasticsearch, I think.

**Comment by crisdarocha** [comment]
Thanks for the heads up @nik9000 and sorry for misplacing the issue! I misread the wiki page!

I'll put the issue at /elasticsearch.
