### ISSUE TITLE
Missing version options for some 1.X builds in Shield and Marvel documentation

### ISSUE THREAD

**Issue by ajoliveira** [elastic/docs#859]
When looking at the docs starting with Shield [version 1.3](https://www.elastic.co/guide/en/shield/shield-1.3/index.html), there are missing options/links to the 1.4, 1.5, 1.6 and 1.7 releases.  These are available in the ES side of [docs](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/index.html), for example.

Also, trying to navigate to the URL directly, results in a 404 error - ex: [version 1.7](https://www.elastic.co/guide/en/shield/shield-1.7/index.html) so if they exist, they are not using the same URL format.

**Comment by debadair** [comment]
The versioning scheme for Shield was not aligned with the Elasticsearch versions at that point in time. Refer to the [Shield installation docs](https://www.elastic.co/guide/en/shield/shield-1.3/installing-shield.html) for the version compatibility information.
