### ISSUE TITLE
"On this page" section in docs is showing "<h2>" tag in the browser

### ISSUE THREAD

**Issue by sylvie777** [elastic/docs#874]
From @jarpy:

On the [public site](https://www.elastic.co/guide/en/logstash/current/environment-variables.html):

![image](https://user-images.githubusercontent.com/119659/57268035-9f994100-70c5-11e9-8890-8a6f033f3ea0.png)

**Comment by jarpy** [comment]
Sorry @sylvie777, I originally opened the issue here in `docs`, but transferred it to your repo when there was no response.

**Comment by sylvie777** [comment]
No worries, @jarpy! 

@nik9000 Do you know who can help fix this issue that @jarpy found?

**Comment by sylvie777** [comment]
LGTM @nik9000! Thank you!
