### ISSUE TITLE
Concurrent doc builds cause problems on release day

### ISSUE THREAD

**Issue by schersh** [elastic/docs#890]
It seems that some recent change in our Jenkins build is allowing for scheduled builds to run concurrently with other jobs. On yesterday's release day, when I kicked off a full rebuild of all of the books, the automated jobs continued to run (see below).

This caused the full build to fail to write the changes to the built-docs repo because of those other "more recent" builds. To complete the release, I had to trigger a new full build, and then manually cancel all of the automated jobs until that full build completed. 

<img width="580" alt="Screen Shot 2019-05-20 at 9 30 34 AM" src="https://user-images.githubusercontent.com/13408456/58106857-c7ed6900-7bb6-11e9-8065-fbca3dfe3fa1.png">

**Comment by lcawl** [comment]
I forgot to get a snapshot of the console output when that #9460 failed, but it got to the point where it successfully checked the links then said it couldn't write because there were changes that it didn't have (I assume related to those #9461 and #9462 that had started and ended while it was running).

**Comment by nik9000** [comment]
> It seems that some recent change in our Jenkins build is allowing for scheduled builds to run concurrently with other jobs. On yesterday's release day, when I kicked off a full rebuild of all of the books, the automated jobs continued to run (see below).

This isn't a thing I *intentionally* did. I wonder how that happened!

**Comment by nik9000** [comment]
It looks like the option has been flipped. I'll open a PR to unflip it.

**Comment by lcawl** [comment]
FYI this situation occurred again today while doing a full rebuild for the new branches. I had to cancel two builds that tried to start while one was still in progress:
![image](https://user-images.githubusercontent.com/26471269/58214785-d8334000-7cab-11e9-8b6e-2c07bc309804.png)
