### ISSUE TITLE
Extra problematic edit link

### ISSUE THREAD

**Issue by lcawl** [elastic/docs#903]
There's an extra “edit” link at the very top of this file: https://www.elastic.co/guide/en/elasticsearch/reference/master/ml-put-job.html

![image](https://user-images.githubusercontent.com/26471269/58571803-584b2f80-81ef-11e9-8fe0-065d45b6ecc7.png)

If you click it, it takes you to an inappropriate location.  If I click the next lower link, it takes me to the right place (https://raw.githubusercontent.com/elastic/elasticsearch/master/docs/reference/ml/apis/put-job.asciidoc).

The pages before and after this one don’t seem to have the problematic edit link in the title section.  There are no overrides specified for this file (it’s included here: https://raw.githubusercontent.com/elastic/elasticsearch/master/docs/reference/ml/apis/ml-api.asciidoc).

NOTE: The same problem occurs when you use the --asciidoctor build option too.

**Comment by nik9000** [comment]
This is caused by the link that looks like `see <<ml-apimodelplotconfig>>`. I believe link is part of the title and is being absorbed. I think I can track it down!
