### ISSUE TITLE
"xmllint" --nonet --noout --valid "/out/html_docs/README.xml" returned non-zero exit status 4

### ISSUE THREAD

**Issue by pouledodue** [elastic/docs#909]
`./build_docs --doc README.asciidoc --pdf`

```INFO:build_docs:a2x: ERROR: "xmllint" --nonet --noout --valid "/out/html_docs/README.xml" returned non-zero exit status 4```

**Comment by nik9000** [comment]
PDF is on my list but not super high to be honest.

**Comment by pouledodue** [comment]
I need a fix before 2024

**Comment by debadair** [comment]
Duplicate ofhttps://github.com/elastic/docs/issues/61

**Comment by gtback** [comment]
We don't support the `--pdf` option anymore (as of #1394). As mentioned there, if we support it in the future we'll be rewriting it anyway.
