### ISSUE TITLE
elastic website CPU / memory hog?

### ISSUE THREAD

**Issue by missinglink** [elastic/docs#91]
Firstly; apologies for opening this issue here, it's not specific to the docs, the issue seems to affect a bunch of pages on the `www.elastic.co` domain.

If I open up a page such as https://www.elastic.co/downloads/elasticsearch in chrome and have `top` in another window open, I can see that the page uses 100% utilization of a single core and the RAM usage starts to climb.

Having 4 tabs open is enough for my computer to go crazy bonkers.
After some time chrome will crash the tab.
It's been happening for some weeks now.

Maybe it's only me? Could someone please confirm/deny they see the same thing?

Also; if we are mining bitcoin, can I haz some plz?

```chrome: Version 49.0.2623.47 beta (64-bit)```

**Comment by missinglink** [comment]
sounds like it's just me, closing.

**Comment by missinglink** [comment]
Weirdly enough, I upgraded to `chrome: 51.0.2704.54 beta (64-bit)` and it still happens for me, so I don't know what's going on.

**Comment by clintongormley** [comment]
I'm on Version 50.0.2661.102 (64-bit) on OSX El Capitan, and the page is just fine.  What OS are you on?  What does the Chrome taskmanager say?  Do you see any weird activity in the developer console?

**Comment by xeraa** [comment]
I'd try an incognito window (shift + cmd + n), which starts from a clean state and doesn't use any (or most?) plugins. I've had adblockers, cookies,... do weird stuff every now and then.
