### ISSUE TITLE
Should we have a minimum docker version?

### ISSUE THREAD

**Issue by nik9000** [elastic/docs#918]
It looks like older versions of docker cause it not to properly clean up the image when you ctrl-c. I've never personally had the problem but it might make sense to be a bit defensive about this especially given docker's habit of making drastic changes in minor releases.

**Comment by gtback** [comment]
I'd argue no. We don't seem to do anything too fancy with Docker, and (though I know this has happened in the past) I haven't heard of any issues related to old/incompatible versions of Docker. Of course, if that happens, someone can always open an issue.
