### ISSUE TITLE
[shield] Update documentation about shield+marvel (for the private repository https://github.com/elastic/x-plugins.git)

### ISSUE THREAD

**Issue by sbadia** [elastic/docs#93]
Hi!

It's more an issue for the private repository https://github.com/elastic/x-plugins.git (but this repo is private, so I put this here :-)).

Refs. this topic [issue-with-action-auto-crate-index](https://discuss.elastic.co/t/marvel-shield-issue-with-action-auto-create-index/) on elastic discourse.

We should maybe add a note in the shield documentation about `action.auto_create_index`

**Comment by clintongormley** [comment]
This issue was moved to elastic/x-plugins#2423

**Comment by clintongormley** [comment]
Moved this to x-plugins, thanks
