### ISSUE TITLE
sincedb documentation incorrect.

### ISSUE THREAD

**Issue by robin13** [elastic/docs#94]
Looks like the [default path](https://github.com/elastic/logstash/commit/4baf29dc5f76a05c3c1486d56bc7a973b0825f1f) is now $LOGSTASH_HOME and not $HOME for sincedb_path

https://www.elastic.co/guide/en/logstash/current/plugins-inputs-file.html#plugins-inputs-file-sincedb_path

**Comment by clintongormley** [comment]
Please open against the logstash repo
