### ISSUE TITLE
Table columns don't wrap correctly

### ISSUE THREAD

**Issue by jrodewig** [elastic/docs#987]
#977 changed the styling for Elastic docs. Column wrapping for tables is now off.

Credit to @lcawl for spotting the issue.

### Before example
<img width="766" alt="column-wrap-before" src="https://user-images.githubusercontent.com/40268737/61250084-d1adcb80-a724-11e9-891f-67af794dc6be.png">

### After example
<img width="779" alt="column-wrap-after" src="https://user-images.githubusercontent.com/40268737/61250096-d8d4d980-a724-11e9-8157-5d22dd1b01b4.png">

**Comment by brianjolly** [comment]
This looks fixed on production. Thank You @cnbishop!

@jrodewig could you please verify you also see it fixed? Thanks!

**Comment by jrodewig** [comment]
Confirmed. This looks fixed. Closing the issue.

**Comment by karenzone** [comment]
Hi team. Found a new example of table wrapping issues in https://www.elastic.co/guide/en/logstash/current/plugins-outputs-cloudwatch.html

<img width="1577" alt="Screen Shot 2019-07-17 at 9 15 42 AM" src="https://user-images.githubusercontent.com/35154725/61380225-f9ad4400-a876-11e9-80c9-9981d81deb73.png">

**Comment by psanz-estc** [comment]
HI there

This one is not ok either:

https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update-by-query.html

<img width="999" alt="Captura de pantalla 2019-07-22 a las 9 49 14" src="https://user-images.githubusercontent.com/44199691/61615315-001c3100-ac66-11e9-9010-8e812bb80195.png">

**Comment by nik9000** [comment]
@psanz-estc, that table looks ok to me in Firefox/desktop. Is it ok for you now? If not how are you looking at it?

@karenzone, that table looks ok to me too now. How is it for you?

**Comment by karenzone** [comment]
@nik9000   Yes. That table and another that was misbehaving are wrapping correctly now. Thank you!

**Comment by psanz-estc** [comment]
Hey @nik9000 , now it looks ok!! When I checked a couple of days ago (with Chrome and Firefox on my MBP)  the wrapping looked incorrect...

**Comment by jrodewig** [comment]
Closing this issue. Feel free to re-open if this pops up again.

**Comment by crisdarocha** [comment]
Sorry to bother, but still a frequent issue. Chrome on MacBookPro

One example is this one. 

https://www.elastic.co/guide/en/watcher/current/configuring-default-internal-ops-timeouts.html

Thanks in advance!

**Comment by crisdarocha** [comment]
<img width="763" alt="Screenshot 2019-07-25 at 19 24 03" src="https://user-images.githubusercontent.com/36699845/61895704-932dc300-af13-11e9-95b6-928392afd7ea.png">

**Comment by brianjolly** [comment]
Hi @crisdarocha, could you double check if your browser has cached css?

If you see the issue on other pages please let us know. Thanks for the help!

Here is the page with a fresh Chrome:

<img width="1393" alt="Screen Shot 2019-07-25 at 10 39 36 AM" src="https://user-images.githubusercontent.com/140304/61896037-ec243980-aec8-11e9-97d1-873625795c4d.png">

**Comment by crisdarocha** [comment]
Sorry @brianjolly, copied the wrong link in my post! Too many tabs opened!

https://www.elastic.co/guide/en/watcher/current/actions.html

Cleared the cache, but still the same.

**Comment by brianjolly** [comment]
I see, thanks @crisdarocha!

**Comment by lcawl** [comment]
Also table 25 here: https://www.elastic.co/guide/en/elastic-stack-overview/master/actions-email.html

**Comment by debadair** [comment]
The reported issues appear to be fixed now. (But tables are a recurring hobgoblin...)
