### ISSUE TITLE
NOTE blocks are capitalized

### ISSUE THREAD

**Issue by lcawl** [elastic/docs#988]
Since the stylesheet changes took effect (I think in https://github.com/elastic/docs/pull/977), admonition blocks are converted to all caps. For example, see https://www.elastic.co/guide/en/elasticsearch/reference/master/ml-close-job.html

![image](https://user-images.githubusercontent.com/26471269/61250477-a8814100-a70c-11e9-8cef-62087a2b535a.png)

I don't think this looks great

**Comment by lcawl** [comment]
Some of them are both capitalized and turned red:

![image](https://user-images.githubusercontent.com/26471269/61329557-763a1700-a7d2-11e9-8b70-81236e7c6e7a.png)

That example is in https://www.elastic.co/guide/en/elasticsearch/reference/master/backup-cluster-configuration.html

**Comment by brianjolly** [comment]
This is looking fixed now on production. Thank You @cnbishop!

@lcawl could you please verify on your end too? Thanks!

**Comment by lcawl** [comment]
LGTM, thanks!
