### ISSUE TITLE
xpack badge floats over dropdowns

### ISSUE THREAD

**Issue by bmorelli25** [elastic/docs#989]
If a page title has the xpack badge, it floats over the top of the menu drop-down:

<img width="777" alt="Screen Shot 2019-07-15 at 3 24 21 PM" src="https://user-images.githubusercontent.com/5618806/61253124-cce11b80-a714-11e9-9b74-ddb5a9d2c78d.png">

**Comment by brianjolly** [comment]
This should be fixed now on production. Thanks @cnbishop!

@bmorelli25 , can you please verify it looks good on your end now? Thanks!

**Comment by bmorelli25** [comment]
Thank you, looks good on my end!
