### ISSUE TITLE
Links not highlighted in documentation

### ISSUE THREAD

**Issue by lcawl** [elastic/docs#990]
Since the stylesheet changes took effect ( #977), you can no longer tell that text is a link until you hover over it. 

For example:
![image](https://user-images.githubusercontent.com/26471269/61253818-382bed00-a717-11e9-8582-3faa6039a9d8.png)

Only after you hover the text does it become highlighted:
![image](https://user-images.githubusercontent.com/26471269/61253862-5db8f680-a717-11e9-9f40-3ecae32af57f.png)

**Comment by brianjolly** [comment]
Links are highlighted again on production. Thanks @cnbishop!

@lcawl can you please also verify the fix? Thanks!

**Comment by lcawl** [comment]
LGTM, thanks!
