### ISSUE TITLE
Code blocks should be monospaced

### ISSUE THREAD

**Issue by karenzone** [elastic/docs#992]
Code samples are appearing in regular type, but should be monospaced.

<img width="978" alt="Screen Shot 2019-07-16 at 9 18 42 AM" src="https://user-images.githubusercontent.com/35154725/61306363-77f7e080-a7ba-11e9-87a1-400eb4c9ba54.png">

**Comment by sylvie777** [comment]
@karenzone This has been updated. Are you still experiencing the issue? Here's a sample page:

https://www.elastic.co/guide/en/logstash/7.2/plugins-inputs-azure_event_hubs.html

![Screen Shot 2019-07-16 at 11 34 15 PM](https://user-images.githubusercontent.com/782265/61352455-3ef35680-a822-11e9-9742-092cc430c155.png)

cc @brianjolly

**Comment by karenzone** [comment]
@sylvie777 I spot-checked several examples, and this issue appears to be resolved.  Thank you!
