### ISSUE TITLE
Link back to Documentation is missing

### ISSUE THREAD

**Issue by karenzone** [elastic/docs#993]
Missing link back to documentation home page which makes it easier to navigate between books
![image (1)](https://user-images.githubusercontent.com/35154725/61306802-31ef4c80-a7bb-11e9-932c-22048fc3b2f0.png)

**Comment by lcawl** [comment]
FYI Here's a screenshot of what it used to look like:

![image](https://user-images.githubusercontent.com/26471269/61313540-7d036280-a7af-11e9-9dd6-577eac142bef.png)

The placement doesn't really matter to me too much, as long as there's a quick one-click way to get to the rest of the library.

**Comment by brianjolly** [comment]
Hi @nik9000 , I added the following to `resources/web/template.html`  https://github.com/elastic/docs/pull/1000. Would you mind kicking off a stage build to test it? Thanks!!

**Comment by nik9000** [comment]
> Hi @nik9000 , I added the following to `resources/web/template.html` #1000. Would you mind kicking off a stage build to test it? Thanks!!

I checked it locally by just building a single doc and it looked good. I can do a staging build too though.
