### ISSUE TITLE
Branch selector drop-down is huge

### ISSUE THREAD

**Issue by bmorelli25** [elastic/docs#999]
The branch selector drop-down is now huge. Can we change the height to maybe not take up so much screen space?

<img width="747" alt="Screen Shot 2019-07-17 at 8 13 01 AM" src="https://user-images.githubusercontent.com/5618806/61387338-cf558980-a86a-11e9-9092-50ee3947ad7b.png">

**Comment by nik9000** [comment]
This looks good now! I'm not super sure what happened, but it is ok now.
